### ISSUE TITLE
device.dimmer bulb icon not updating

### ISSUE THREAD

**Issue by lolouk44** [Martin-Gleiss/smartvisu#100]
Not sure if this is down to SmartVISU or DomotiGa, but when DomotiGa switches off a dimming light, although I see the dimmer slider go to 0 / left, the bulb icon on the left is not updated. If I refresh the page, this is corrected.

**Comment by lolouk44** [comment]
Just to confirm this also happens with V2.8

**Comment by lolouk44** [comment]
In case it helps, this also appears on a range of other items, including:

- basic.dual
- device.rtr
- basic.shifter

**Comment by smaiLee** [comment]
I can't test this because I don't use DomotiGa.
This seems to be a problem of the driver or the DomotiGa websocket itself.

Can you check what's sent by DomotiGa on websocket by clicking e.g. a basic.dual? By using Chrome browser's developer tools you can inspect websocket communication, see https://kaazing.com/inspecting-websocket-traffic-with-chrome-developer-tools/ for instructions.

You could try to exclude other reasons (like a blocking script or any other interference) by creating a new pages folder with just one page and one widget.

**Comment by lolouk44** [comment]
Hi Stefan,
Sorry it took so long.

Here is what I get:
`/* smartVISU, Martin Gleiß, 2012 - 2015, GPL [http://www.gnu.de] */
var io={address:"",port:"",read:function(a){},write:function(a,c){io.send({cmd:"item",id:a,val:c});widget.update(a,c)},trigger:function(a,c){io.send({cmd:"trigger",type:a,id:c})},init:function(a,c){io.address=a;io.port=c;io.open()},run:function(a){1<io.socket.readyState?io.open():(widget.refresh(),io.monitor())},version:"0.4",socket:!1,open:function(){io.socket=new WebSocket("ws://"+io.address+":"+io.port+"/");io.socket.onopen=function(){io.send({cmd:"proto",ver:io.version});io.monitor()};io.socket.onmessage=
function(a){var c,d;a=JSON.parse(a.data);switch(a.cmd){case "item":for(var b=0;b<a.items.length;b+=2)c=a.items[b],d=a.items[b+1],widget.update(c,d);break;case "series":widget.update(a.items.id,a.items.plotdata);break;case "dialog":notify.info(a.header,a.content);break;case "log":c=widget.get(a.name);for(b=0;b<a.log.length;b++)c.unshift(a.log[b]),50<=c.length&&c.pop();widget.update(a.name);break;case "proto":a=a.ver,a!=io.version&&notify.info("Driver: DomotiGa","Protocol version mismatch<br />Driver is at version v"+
io.version+"<br />DomotiGa is at version v"+a)}};io.socket.onerror=function(a){notify.error("Driver: DomotiGa","Could not connect to the DomotiGa server!<bre >?Websocket error: "+a.data+".")};io.socket.onclose=function(){notify.error("Driver: DomotiGa","No connection with the DomotiGa server!")}},send:function(a){1==io.socket.readyState&&io.socket.send(unescape(encodeURIComponent(JSON.stringify(a))))},monitor:function(){widget.listeners().length&&io.send({cmd:"monitor",items:widget.listeners()});
var a=[];widget.plot().each(function(c){c=widget.explode($(this).attr("data-item"));for(var d=0;d<c.length;d++){var b=c[d].split(".");if(!a[c[d]]&&!widget.get(c[d])&&b instanceof Array&&widget.checkseries(c[d])){var e=c[d].substr(0,c[d].length-4-b[b.length-4].length-b[b.length-3].length-b[b.length-2].length-b[b.length-1].length);io.send({cmd:"series",item:e,mode:b[b.length-4],tmin:b[b.length-3],tmax:b[b.length-2],count:b[b.length-1]});a[c[d]]=1}}});widget.log().each(function(a){io.send({cmd:"log",
name:$(this).attr("data-item"),max:$(this).attr("data-count")})})},close:function(){0<io.socket.readyState&&io.socket.close();io.socket=null}}; `

I can also see an error:
![image](https://cloud.githubusercontent.com/assets/4587746/26050298/fbfba342-3955-11e7-8ffe-8be8dfb253f4.png)

Is this enough to help?

**Comment by smaiLee** [comment]
I did not mean the driver script but the WebSocket communication itself.
But you're close. In your screenshot of developer tools you did filter network communication for WS. The result is covered by the console window.

The script error my have a correlation, but it does not necessarily have to.

**Comment by lolouk44** [comment]
OK thanks, I think I got what you want :)
Below is a screenshot showing exactly what I'm experiencing.
When I activate the Normal mode (so send "On" to MoodSceneNormal_Value1, I have a rule in DomotiGa to change all other modes to Off.
now for some reason the mode that was previously selected (Manual) doesn't automatically switch off. (though from the screenshot it seems it does and then comes back to On)
![image](https://cloud.githubusercontent.com/assets/4587746/26225425/06effce6-3c1f-11e7-9c73-e0caabec2ab5.png)

If I refresh the page, I get the correct status for MoodSceneNormal

If however I have 2 separate basic.switch pointing to both MoodScene devices in DomotiGa, I get the correct status in real time.

Does this help?

**Comment by wvhn** [comment]
Support for Domotiga ended. Driver is not being distributed any more. Issue is not seen on installations w/ other drivers.
