### ISSUE TITLE
multimedia.image with refresh not working for multiples images in 2.8

### ISSUE THREAD

**Issue by lolouk44** [Martin-Gleiss/smartvisu#104]
I am using multimedia.image to stream my CCTVs.
In 2.7 it worked really well, but in 2.8 I get the same image (the last one) being repeated / cloned on all other images.

**Comment by lolouk44** [comment]
Anyone had the chance to look into this yet?
It's the only issue I have left to complete the move to 2.8 on my "production" environment...

Thanks

**Comment by lolouk44** [comment]
Sorry to push, but I was wondering whether this can be looked into? or am I the only one with this issue?
Thanks

**Comment by smaiLee** [comment]
Do I take you right:
There are multiple multimedia.image widgets on same page and all of them show the same image instead of different ones?

**Comment by lolouk44** [comment]
Hi,

Thanks for coming back. exactly. I have 3 CCTV streams (so hyperlink to JPGs) which should show up. this is the case once the page is loaded, but as soon as they refresh, the last image is copied across to all multimedia.image instead of refreshing each one independently.

Thanks

**Comment by smaiLee** [comment]
Could you check please if the problem is gone by replacing widgets/multimedia.html by [this one](https://raw.githubusercontent.com/Martin-Gleiss/smartvisu/5475ff2f686038c9b896c4cf2e3a64bc92c88b60/widgets/multimedia.html)?

**Comment by lolouk44** [comment]
Fixed :) 

Thanks

**Comment by smaiLee** [comment]
I merged the fix to master and develop.
