### ISSUE TITLE
Orange svg icons

### ISSUE THREAD

**Issue by lolouk44** [Martin-Gleiss/smartvisu#106]
Thought I'd share the orange svg icon library I created in case someone else needs it
[or.zip](https://github.com/Martin-Gleiss/smartvisu/files/516448/or.zip)

**Comment by smaiLee** [comment]
Thank you, but actually there are no colored svg icons necessery because they can be colored by css.

**Comment by lolouk44** [comment]
Thanks. can you share some guidelines on how best to approach this?

**Comment by smaiLee** [comment]
You can find this at the documentation for simple [html icons](http://docu.smartvisu.de/2.8/index.php?page=design/design_icons) or the widget you use e.g. [basic.symbol](http://docu.smartvisu.de/2.8/index.php?page=basic/widget_basic.symbol).

**Comment by lolouk44** [comment]
Thanks. I think there's an error in the doc, namely in [html icons](http://docu.smartvisu.de/2.8/index.php?page=design/design_icons)
It states
`<img class="icon icon1" src="{{ icon }}light_light.svg" />`
but what works for me is:
`<img class="icon icon1" src="{{ icon0 }}light_light.svg" />`
(there is a missing "0" just before the svg file name...

**Comment by smaiLee** [comment]
I 'm afraid your right.
