### ISSUE TITLE
auto refresh plots

### ISSUE THREAD

**Issue by lolouk44** [Martin-Gleiss/smartvisu#111]
Hi,

I was wondering whether it's possible to get plot charts to auto refresh?
I believe Highcharts offers this option so I was hoping it can be included in SmartVISU?

Thanks :)

**Comment by psilo909** [comment]
from what i know they already DO refresh?

**Comment by lolouk44** [comment]
I don't believe they do.
Just checked again and the data only gets updated when I refresh the page.
In case it makes a difference the data plotted is from DomotiGa.

**Comment by msinn** [comment]
They do, but it takes some time (too much for my taste). To test, just let your visu sit for quite some time (half an hour or so) and check if an update occurred.

**Comment by psilo909** [comment]
in @msinn and my case smarthomeNG.. this could be a reason, dont know anything about the impl. of your JS "driver"

**Comment by lolouk44** [comment]
I can confirm that it does not automatically refresh (at least DomotiGa data):
Below screenshot taken at 19:23 today clearly shows the last date point at 12:52 and the screen had been left all day since my last post
![plot_no_refresh](https://cloud.githubusercontent.com/assets/4587746/19419755/41a2bc08-93d6-11e6-9f25-17b6109efdd4.png)

**Comment by wvhn** [comment]
shNG items DO refresh automatically by subscribing series items from the backend's websocket plugin.
To refresh plots, the backend needs to actively update the series.

Closed because of Domotiga EOL.
