### ISSUE TITLE
GoogleV3 overwriting events which take whole day

### ISSUE THREAD

**Issue by psilo909** [Martin-Gleiss/smartvisu#112]
The GoogleV3 implementation is overwriting multiple events that take place over the same whole day as $start is used as array index:
https://github.com/Martin-Gleiss/smartvisu/blob/develop/lib/calendar/service/googleV3.php#L151

i solved it by adding a new index $i=0 which is incremented and used instead of $start.

I suppose the same happens when events take place at the same timespan.

**Comment by smaiLee** [comment]
The use of this index seemes to be sorting, see [line 170](https://github.com/Martin-Gleiss/smartvisu/blob/develop/lib/calendar/service/googleV3.php#L170).

A simple solution would be to combine this two indexes, e.g. $events[$start.'_'.$i]. So you still can order but there is a unique index.

**Comment by psilo909** [comment]
testing your proposal now

**Comment by smaiLee** [comment]
GoogleV3 is deprecated, so closing this.
