### ISSUE TITLE
Can't call docu index page if jump page was configuration

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#121]
If the first page (which is the only fully loaded) is index.php?page=config the link to the start page does not work. This happens among others by saving the configuration.

The reason is an exception on calling prettyPrint(). The _vendor/google.prettify/src/prettify.js_ is loaded in the {% block head %} of /pages/docu/index.html. But the header is only evaluated on fully loaded page and not on navigating.

This problem is not limited to configuration page, it will likely happen on any page that uses {% block head %}

**Comment by wvhn** [comment]
could not reproduce the issue any more.
