### ISSUE TITLE
Different use / displaying of hints

### ISSUE THREAD

**Issue by Tom-Bom-badil** [Martin-Gleiss/smartvisu#123]
The use of hints in the smartVISU is not consistent.

basic.symbol, basic.switch, popup links with < a > < / a > etc all display hints in a different way. As an example, basic.symbol always shows system date/time when the mouse hovers over it, no matter what the content / meaning of the symbol is.

I would like to suggest to either introduce a new argument 'hint' (string) in the definition of basic.xxx (prefered option in order to make it user definable, default ''), or just to block the displaying of hints completely.

**Comment by smaiLee** [comment]
I removed the pointless date tooltip on `basic.symbol` and added tooltips containing value in percent on `basic.shifter` and dynamic `icons.*` (except `icon.clock` and thereby `clock.iconclock`, they show the time).
But unfortunately Chrome does not display tooltips on svg.

I think an extra argument would be too much.
