### ISSUE TITLE
Return to home page on inactivity (configurable)

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#127]
Integrate the script published on https://knx-user-forum.de/forum/supportforen/smartvisu/1004488-von-den-raumseiten-automatisch-zurück-zur-übersicht?p=1022710#post1022710 as a configuration option.

**Comment by Foxi352** [comment]
If would be very cool to be able to configure the "home" page per device. If you have VISU's in multiple rooms, i personally would prefer the room page of each VISU's specific room as home page. I would love to see a configuration parameter "home page" as global and per device option as are other parameters too.
