### ISSUE TITLE
Keyword-based icons in calendar

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#128]
Icons can only be defined by @icon definition in event description so far.

A more user-friebdli solution could be a dictionary of terms and icons. If a term is found in event title, the corresponding icon is shown.

**Comment by lolouk44** [comment]
Hi,

I welcome that addition. I was actually wondering how to assign icons to calendar events. Do you already have any info you can share and maybe a list of icons (if different than the standard SmartVISU icons)?

Thanks

**Comment by smaiLee** [comment]
Currently I'm working on this. The available icons are the regular ones.

In German I have the configuration set below.
Maybe you could translate this into French or add other relevant terms (I don't know which recycle concept exists in France). As mentioned in the language file issue the terms could also be defined country specific if there are any differences.

```
Grüne Tonne[icon] = message_garbage
Grüne Tonne[color] = green
Blaue Tonne[icon] = message_garbage
Blaue Tonne[color] = #0000FF
Gelbe Tonne[icon] = message_garbage
Gelbe Tonne[color] = #FFFF00
Braune Tonne[icon] = message_garbage
Braune Tonne[color] = #92561c
Graue Tonne[icon] = message_garbage
Graue Tonne[color] = #808080
Schwarze Tonne[icon] = message_garbage
Schwarze Tonne[color] = #808080
Grünabfuhr[icon] = message_garbage
Grünabfuhr[color] = green
Kehricht[icon] = message_garbage
Kehricht[color] = #808080
Altpapier[icon] = message_mail_open
Altpapier[color] = #0000FF

Kino[icon] = scene_scene
Sport[icon] = scene_fitness
Fitness[icon] = scene_fitness
Fussball[icon] = scene_football
Ferien[icon] = weather_summer
Ferien[color] = "rgb(32, 178, 170)"
Urlaub[icon] = weather_summer
Urlaub[color] = "rgb(32, 178, 170)"
Party[icon] = scene_party
Geburtstag[icon] = message_garbage
Feier[icon] = scene_drink
```

**Comment by lolouk44** [comment]
Hi Stefan,

Thanks for this.
See below translations.
Note1: I direct translated the bins to give people the choice options. I know in the UK different cities have different recycling schemes. I've been living in the UK for too long to remember / know better for France but assume it may also differ per city.
Note2: I guess you did a typing mistake for the Geburtstag icon?
Note3: Have you thought of connecting / pulling icons from https://materialdesignicons.com/ ?

German	French	English				
Grüne Tonne	Poubelle Verte	Green Bin	[icon] = message_garbage			
Grüne Tonne	Poubelle Verte	Green Bin	[color] = green			
Blaue Tonne	Poubelle Bleue	Blue Bin	[icon] = message_garbage			
Blaue Tonne	Poubelle Bleue	Blue Bin	[color] = #0000FF			
Gelbe Tonne	Poubelle Jaune	Yellow Bin	[icon] = message_garbage			
Gelbe Tonne	Poubelle Jaune	Yellow Bin	[color] = #FFFF00			
Braune Tonne	Poubelle Marron	Brown Bin	[icon] = message_garbage			
Braune Tonne	Poubelle Marron	Brown Bin	[color] = #92561c			
Graue Tonne	Poubelle Grise	Grey Bin	[icon] = message_garbage			
Graue Tonne	Poubelle Grise	Grey Bin	[color] = #808080			
Schwarze Tonne	Poubelle Noire	Black Bin	[icon] = message_garbage			
Schwarze Tonne	Poubelle Noire	Black Bin	[color] = #808080			
Grünabfuhr	Déchets de jardin	Garden Waste	[icon] = message_garbage			
Grünabfuhr	Déchets de jardin	Garden Waste	[color] = green			
Kehricht			[icon] = message_garbage			
Kehricht			[color] = #808080			
Altpapier	Vieux Papiers	Waste Paper	[icon] = message_mail_open			
Altpapier	Vieux Papiers	Waste Paper	[color] = #0000FF			
						
Kino	Cinéma	Movies	[icon] = scene_scene			
Sport	Sport	Sport	[icon] = scene_fitness			
Fitness		Gym	[icon] = scene_fitness			
Fussball	Football	Football	[icon] = scene_football			
Ferien	Jour Férié	Bank Holiday	[icon] = weather_summer			
Ferien	Jour Férié	Bank Holiday	[color] = "rgb(32, 178, 170)"			
Urlaub	Vacances	Holidays	[icon] = weather_summer			
Urlaub	Vacances	Holidays	[color] = "rgb(32, 178, 170)"			
Party	Fête	Party	[icon] = scene_party			
Geburtstag	Anniversaire	Birthday	[icon] = message_garbage			
Feier	Célébration	Celebration	[icon] = scene_drink

**Comment by lolouk44** [comment]
attaching an excel file as formatting got screwed above.
[Vodafone Engineers + PERT.xlsx](https://github.com/Martin-Gleiss/smartvisu/files/764803/Vodafone.Engineers.PERT.xlsx)

**Comment by lolouk44** [comment]
attaching excel file as formatting got screwed
[SmartVISU_Calendar_Icons.xlsx](https://github.com/Martin-Gleiss/smartvisu/files/764808/SmartVISU_Calendar_Icons.xlsx)

**Comment by smaiLee** [comment]
Thanks, I did add them with some minor modifications.
And I made a new icon scene_birthday.svg as there was no appropriate one.

I will think about Material Design Icons. As the existing KNXUF Icon Set is designed for building control there are actually some usefull icons lacking.
