### ISSUE TITLE
optionally show switch of device.dimmer on the right side

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#131]
Add parameter to show the switch of device.dimmer on the right side instead of left side.

**Comment by lolouk44** [comment]
Hallo Stefan,

Related to this, I'm not sure if the issue is with SmartVISU or DomotiGa, but when DomotiGa switches the device off, although the dimmer bar is correctly updated, the switch icon light bulb does not get updated. I have to manually refresh the page. See #100 
Thanks

**Comment by wvhn** [comment]
done with #257
