### ISSUE TITLE
Missing Wheater Icon: Ice Pellets

### ISSUE THREAD

**Issue by lolouk44** [Martin-Gleiss/smartvisu#132]
Hi,

I have a missing icon today for a weather state: Ice Pellets.
![screenshot - 20_01_2017 14_49_03](https://cloud.githubusercontent.com/assets/4587746/22157373/5cc4502e-df2f-11e6-940e-f9bec0ea75a8.png)

I tried to add a line to lib/weather/service/wunderground.com.php but I can't figure out what to enter.
`$icon['icepellets'] = 'cloud_16';`
Tried icepellets, ice pellets and ice_pellets, none work

Any idea?

**Comment by smaiLee** [comment]
This is interesting, according to [wunderground documentation](https://www.wunderground.com/weather/api/d/docs?d=resources/phrase-glossary&_ga=1.15970870.1837785816.1468438635#forecast_description_phrases) ice pellets do not exist as a regular condition.
So I'm afraid you have to ask [wunderground](https://apicommunity.wunderground.com/weatherapi) which icon code is sent (or have a look at wunderground reponse next time you get ice pellets.)

**Comment by lolouk44** [comment]
Thanks, I have no idea if I'll eve see it again, but in case I do, what are you after? Are you able to send some guidance?
I had a look at the xml using the API key I have, but could not find anything with Ice Pellets.
Thanks

**Comment by smaiLee** [comment]
This could actually be the problem: Normally there should be an element 'icon' in the xml.

**Comment by lolouk44** [comment]
That's what I thought. So wondering where this icon came from then... I'll Keep an eye on this.. closing this issue for now
