### ISSUE TITLE
Backend driver selection list empty

### ISSUE THREAD

**Issue by StefanSverige** [Martin-Gleiss/smartvisu#133]
In the 2.9 development branch, I can not select a driver. The dialog is just empty. I can also not find the driver configuration line `define('config_driver', 'smarthome.py');` any longer.
If I add the line manually into the config.php it is still not shown in the config dialog, but the communication start to work.

**Comment by smaiLee** [comment]
Thank you for your feedback.
I did note this already and have fixed it locally, fix will be pushed tomorrow.

**Comment by StefanSverige** [comment]
Great,
now it works.
