### ISSUE TITLE
wunderground icon for Graupel/sleet not shown

### ISSUE THREAD

**Issue by msome** [Martin-Gleiss/smartvisu#134]
SmartVisu shows a null image when Graupel (sleet) is on the weather forecast.

In lib/weather/service/wunderground.com.php inside the function "icon" the following two lines are missing to support "Graupel" (sleet):
```
		$icon['sleet'] = 'cloud_11';
		$icon['chancesleet'] = 'cloud_11';
```

**Comment by hebe2k** [comment]
Had this bug today and tested your fix and it's working.
I created a Pull Request.

**Comment by smaiLee** [comment]
Merged, thank you
