### ISSUE TITLE
Different datapoints to change and update the state of the widget (e.g. in I/O driver eibd)

### ISSUE THREAD

**Issue by balferreira** [Martin-Gleiss/smartvisu#137]
This problem are related to the use of the datapoints. since I've one knx address that is responsible to switch on/off the light (2049 of type 1.001), another one to set a specific value of the light (2051 of type 5.001), and another one to get the value of the light (2053 of type 5.001)
If I set the data-widget="basic.switch" data-item="2053", with 2053 data-item I'm not be able to switch the light on/off, since the datapoint responsible for that is the 2049. And if a set the switch to the 2049, I will not be able to get the state of the light.
My suggestion is: instance of you have a data-item, create two data objects, one to data-write="2049" and another data-read="2053", and change the base.js to get teh data-read. I just test this change on base.js.

```
update: function (item, value) {
...
$('[data-read*="' + item + '"]').each(function (idx) {
   var items = widget.explode($(this).attr('data-read'));

...


listeners: function () {
		$('[id^="' + $.mobile.activePage.attr('id') + '-"][data-read]').each(function (idx) {
			if (!($(this).attr('data-widget') == 'status.log')) {
				var items = widget.explode($(this).attr('data-read'));
```
And I guess this works.

**Comment by smaiLee** [comment]
As discussed on Gitter I would prefer a solution which allows passing of a sending and one (or multiple?) receiving addresses in the existing item parameter.
Either separated by a character (like , or |) or as a list like [sending, receiving1, receiving2, ...]
For this solution no change of the widgets signature (parameter count) would be necessary.

**Comment by balferreira** [comment]
Ok, that could be another solution and from that perspective this approach has the advantage to not change the widgets signature.

**Comment by balferreira** [comment]
I don't think this approach 
> Either separated by a character (like , or |) or as a list like [sending, receiving1, receiving2, ...]

will work, since you have the items that will contain values (the read ones) in the same array of the item that don't contain values. i.e. data-item='2257,2259', 2257 switch the light on/off (write only), 2259 light state on/off (read only), on base.js when you perform the 
`update: function (item, value)` and after you get items: `var items = widget.explode($(this).attr('data-item')); `  and get the items values `values = widget.get(items); if (widget.check(values))`. when you receive and update **only for 2259** this code will fail:
```
check: function (values) {

		// case: more values
		if (values instanceof Array) {
			for (var i = 0; i < values.length; i++) {
				if (values[i] === undefined || values[i] == null) {
					return false;
				}
			}
		}
		// case: one value
		else if (values === undefined || values == null) {
			return false;
		}

		return true;
	},
```
Since you will get a value of 2259, but the 2257 will be undefined.
I guess that will be necessary to add something else do dapoints in order to differentiate the write datapoint from read datapoint.
Did you think that something like  [s-2257, r-2259, ...] will work?

**Comment by wvhn** [comment]
With #899 it is now possible to put both data points into one item.
Format is "GA_state:GA_control", e.g. "1/0/0:1/0/1" or with data types: "1/0/0/1.001:1/0/1/1.001"
The driver then reads form GA_state and writes to GA_control while the item value is stored under the full item name.
