### ISSUE TITLE
troubleshooting plots

### ISSUE THREAD

**Issue by lolouk44** [Martin-Gleiss/smartvisu#141]
I've recently upgraded to Ubuntu 16.04.
I've had to clear a few issues (one of them being to go down to php 5.6 due to incompatibilities with php 7.0)
Everything is back up and running except my plots.
Seeing as they used to work pre-upgrade and I've not made any change to my smartvisu pages, how might I troubleshoot to see what is failing?

**Comment by smaiLee** [comment]
First I would check what data is sent by i/o backend (which one do you use?)

**Comment by lolouk44** [comment]
Danke Stefan for the quick reply. I use DomotiGa. As all the other sensor data is being sent I'm guessing it's working? (again I've not made changes to DomotiGa)
Is there a way to log what is received by SmartVISU?

**Comment by smaiLee** [comment]
Domotica driver uses WebSockets, so you can use e.g. Developer Tools to debug: Open network tab and click the WebSocket entry.
As the plotting takes place in client browser I don't see how the server affects this.
Only thing the server mades is generating the html. So you can check the html code thats generated fir plot widget by looking for "plot." in page source on browser.

**Comment by lolouk44** [comment]
Thank Stefan.
This is what is in the page source for Plot:

in the head section:
`	<script type="text/javascript" src="vendor/plot.highcharts/highcharts.js"></script>`

in the body section:
`	<div id="AV-Nest_Tracker" data-widget="plot.rtr" data-item="Nest_Thermostat_plot2.avg.1d.now.100, Nest_Thermostat_plot4.avg.1d.now.100, Nest_Thermostat_plot1.avg.1d.now.100"
		data-step="50" data-label="Actual, Set" data-axis="Time, Temperature"
		class="plot"></div>`

Websocket Network Tools shows this:
![screenshot - 13_02_2017 11_16_52](https://cloud.githubusercontent.com/assets/4587746/22881367/064ca676-f1de-11e6-80ba-890b63401c78.png)

Looks like it then stays waiting for data forever?

**Comment by smaiLee** [comment]
HTML seems to be OK.
I think you have to click on this websocket entry to see the data transmitted.

**Comment by lolouk44** [comment]
Thanks.

So far this is what I can see, but not sure it's of any help:

**Headers**
```
**General**
Request URL:ws://www.lolorpi.com:2121/
Request Method:GET
Status Code:101 Switching Protocols
Response Headers
view source
**Response Headers**
Connection:Upgrade
Sec-WebSocket-Accept:DbfZVoisZ/fPZIx0MGuAWlQhcfk=
Upgrade:WebSocket
**Request Headers**
view source
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-GB,en;q=0.8,fr;q=0.6
Cache-Control:no-cache
Connection:Upgrade
Cookie:_ga=GA1.2.463194905.1431374274
Host:www.lolorpi.com:2121
Origin:http://lolorpi.com
Pragma:no-cache
Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits
Sec-WebSocket-Key:uhlppdEx/fq7g03T/NqSyA==
Sec-WebSocket-Version:13
Upgrade:websocket
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
```

**Frames:**
As I've got a single plot.rtr chart, I have 3 gads.
Here's 1 example:
`{cmd: "series", item: "Nest_Thermostat_plot2", mode: "avg", tmin: "1d", tmax: "now", count: "100"}
cmd
:
"series"
count
:
"100"
item
:
"Nest_Thermostat_plot2"
mode
:
"avg"
tmax
:
"now"
tmin
:
"1d"`

 If I copy the data off as HAR is that be of any use to you? ( i need to check what I need to sanitise so I don't compromise on security)

**Comment by smaiLee** [comment]
This seems to be the request from visu to domotica.
Isn't there any response? The header isn't of interesse for me, just the transmitted data.

**Comment by lolouk44** [comment]
Hi Stefan, in the meantime I tried to upgrade to php7 again.
I get the icons updating correctly but also get a red error message on top right.
When I click on it, I get no info/details...
The plots are working however (?)
also not sure if related, but my wordpress page returns an HTTP Error 500
![screenshot - 17_02_2017 12_12_17](https://cloud.githubusercontent.com/assets/4587746/23064854/6219a29a-f50a-11e6-86d8-fe364d61c38b.png)
![screenshot - 17_02_2017 12_12_28](https://cloud.githubusercontent.com/assets/4587746/23064858/648e3068-f50a-11e6-8599-08c8b05a5af8.png)

**Comment by Tom-Bom-badil** [comment]
Just as a side info: I have seen these empty 'unknown errors' popping up regularly in 2.9 while my calendar wasn't configured correctly. Now CalDav is set up the right way, the errors have disappeared. So the warning isn't necessarily connected to plots ...

**Comment by lolouk44** [comment]
Thanks Tom-Bom-Badil (is that your real name? If so really cool :) )
If it helps, my wordpress issue was linked to a plugin, but I have the feeling the plugin itself isn't at fault, it sounds more like I'm missing a php library

These are the ones I have currently installed:

```
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
```

In addition My apache2 error log shows lots of errors.
some catching my eyes are

`[mpm_prefork:notice] [pid 4283] AH00169: caught SIGTERM, shutting down`

`PHP Fatal error:  Class 'SimpleXMLElement' not found in /var/www/html/wordpress/wp-content/plugins/easy-contact-forms/easy-contact-forms-utils.php on line 810`

`PHP Fatal error:  Uncaught Error: Call to undefined function mb_strtolower() in /var/www/html/smartvisu/lib/class_cache.php:26\nStack trace:\n#0 /var/www/html/smartvisu/lib/weather/service/wunderground.com.php(29): class_cache->__construct('wunderground_UK...')\n#1 /var/www/html/smartvisu/lib/service.php(86): weather_wunderground->run()\n#2 /var/www/html/smartvisu/lib/weather/service/wunderground.com.php(166): service->json()\n#3 {main}\n  thrown in /var/www/html/smartvisu/lib/class_cache.php on line 26, referer: http://lolorpi.com/smartvisu/index.php?page=AV`

Any ideas or advice?

**Comment by smaiLee** [comment]
Well, the answer is in your stack trace:
mb_strtolower resp. mbstring extension seems missing: http://php.net/manual/en/mbstring.installation.php
And for wordpress SimpleXML is missing http://php.net/manual/en/simplexml.installation.php. This one is also used in CalDav and in future in iCloud service.

**Comment by lolouk44** [comment]
Thanks. I think I've messed up my system by re-un-installing a mix of php5.6, php7.0 and php7.1
I'll clean the whole lot and will reinstall as it's becoming too complex and messy to troubleshoot. Good news is that SmartVISU is not the issue here :)

**Comment by smaiLee** [comment]
Well, an issue could be that smartVISU requires mbstring which is a non-default extension (according to http://php.net/manual/en/mbstring.installation.php). This should at least be documented.

**Comment by lolouk44** [comment]
Yes SmartVISU works 100% now but like I said even though php7.1-mbstring was installed, I also had to install php7.0-mbstring so defo need a cleanup

**Comment by Tom-Bom-badil** [comment]
_Off topic: Nope, name is borrowed from Mr. Tolkien, luckily they didn't put it in the LotR movies. Using it since the days I acted as a hub in the early offline-networks like Fido/Z etc (long time before a system called 'Internet' became known to the public). Got very much used to the name over the last >25 years , so nowadays it's more or less like being a multiple/split personality ;) ... /tom_

**Comment by lolouk44** [comment]
Feel free to close it
Thanks
