### ISSUE TITLE
Timezone is hardcoded to 'Europe/Berlin'

### ISSUE THREAD

**Issue by lolouk44** [Martin-Gleiss/smartvisu#150]
I think this is probably due to the imminent daylight saving change.
My calendar times are now 1h off (shows 1h later than actual)
I'm not sure what to check as I've not made any changes to SmartVISU or GGL Calendar.
I don't see any place to set my timezone...

**Comment by smaiLee** [comment]
Which service/driver do you use, GoogleV3 or iCal?
And which version of smartVISU, 2.8 (master)?

**Comment by lolouk44** [comment]
Thanks for the quick reply. I tried iCal, (not managed to set up GoogleV3
as always returns an error)
yes I'm on 2.8 master

**Comment by smaiLee** [comment]
Hmm. Does this affect only events before or after daylight saving change (25./26.03.2017) or both of them?

I did just try this myself but could not reproduce. Events on 22.03.2017 10:00 as well as on 29.07.2017 10:00 are shown at right time from my Google calendar.

**Comment by lolouk44** [comment]
All events displayed before and after daylight changing time are offset by +1h
I'm located in the UK if that makes a difference. See if you can set your locale to UK to test?

**Comment by smaiLee** [comment]
And this issue is new?
I did notice that the timezone is set hardcoded to 'Europe/Berlin' in https://github.com/Martin-Gleiss/smartvisu/blob/master/lib/defaults.php#L249
I have to change this for upcoming version.

**Comment by lolouk44** [comment]
I have experienced it a long time ago, but was messing about and as it eventually was sorted I thought maybe a reinstall or other fixed it.
I just tried to change the default timezone to Europe/London in O P T I M A T I O N S (guess that should be optimizations?) but that didn't make any difference

**Comment by lolouk44** [comment]
by they way, is there a doc to setup GoogleV3?

**Comment by lolouk44** [comment]
hold on. fixed.
find an old custom GoogleV3 customised file I used after Google deprecated the V2 api.
Retrieved the client secrets and other tokens from there, and added them to the "official" SmartVISU GoogleV3 and it now works. Will run some tests with the default timezone to see if I can break it again and prove that the timezone was the culprit.
Still would be a nice idea to add a doc on how to set up an API account for GoogleV3 on smartvisu.de as it's far from obvious.

**Comment by lolouk44** [comment]
Sorry for the SPAM, timezone change confirmed as solution.
I'll open a new issue for GoogleV3 Calendar Doc

**Comment by smaiLee** [comment]
This code was written before my time in smartVISU project, so I actually don't know what it is for.
I reopen this as there has to be a change.

AFAIK there is now doc for GoogleV3, just a lengthy [thread](https://knx-user-forum.de/forum/supportforen/smartvisu/40313-google-calendar-update-f%C3%BCr-neue-googleapi) in German knx-user-forum.
The complexity and the missing doc are reasons why i'd like to remove GoogleV3 in a later release if no one improves this (see #90).

**Comment by lolouk44** [comment]
It is complex to setup but the advantage is that you only see future events form "NOW", the ics calendar shows future events from start of today (so it displays events from this morning which are technically in the past)
if you want to remove GoogleV3 happy with it, if you want me to write a translation of the german instructions from above link, happy to help

**Comment by smaiLee** [comment]
Well, the content of above link seems not very clear in German even :unamused:
First there has to be configuration options. It's not reasonable that one has to edit the source code file.

I will see if I find some time and passion to do this myself.

**Comment by lolouk44** [comment]
This was what I followed to set up my custom GoogleV3 calendar.
I've done it once, I'm sure I can do it again and document if you're interested, then you can review the steps / code to make it user-friendly...

**Comment by smaiLee** [comment]
Yes, please do this :+1:

**Comment by lolouk44** [comment]
The Google API interface has changed a bit since the German instructions.
I've recreated them to reflect the new interface, wording and steps.
[googleV3 Setup Instructions.zip](https://github.com/Martin-Gleiss/smartvisu/files/834544/googleV3.Setup.Instructions.zip)

**Comment by smaiLee** [comment]
Thank you.

I did some study last night and implemented a prototype to work out the possibilities.
See my conclusion in #90

**Comment by lolouk44** [comment]
Hi Stefan,

The refresh token doesn't appear to expire or need caching. I've used the
same token ever since v2 apologies for deprecated and never had to replace
or regenerate it. So I guess we can store our in the same way we store the
other secret keys

**Comment by smaiLee** [comment]
Not the refresh token but the access token. This is valid for an hour.
The refresh token is used to get the access token. The current implementation of GoogleV3 does request a new access token at every call. But as the original developer wrote on forum, this is not reasonable for performance reasons.

**Comment by lolouk44** [comment]
Oh ok, didn't realise that. I'll let you decide on this then
