### ISSUE TITLE
Integrate Fritz!Box via TR-064

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#152]
See https://knx-user-forum.de/forum/supportforen/smartvisu/38552-fritz-box-telefonliste-via-tr-064

Check if other Fritz!Box Services are needed anymore.

**Comment by wvhn** [comment]
only tr-064 has been converted to php8 compatibility. The others have been set to deprecated.
We'll see in the forum whether update of other services will be requested,
