### ISSUE TITLE
Wunderground location selection

### ISSUE THREAD

**Issue by lolouk44** [Martin-Gleiss/smartvisu#153]
Might be my issue, but tonight SmartVISU is throwing a "Read request failed!" error for Wunderground.
Weather data is not being displayed.
I just logged in on Wunderground and also pulled a JSON request with my key and all works.
This is really odd as I don't believe I've changed anything...
What's even more odd is that if I set the weather to be offline, I get no error message but Weather data is still being displayed (and I deleted the Temp folder) is it still maybe in some cache?
Not too sure what to do from here...

**Comment by lolouk44** [comment]
Just one more piece of info. Until now my location was set to UK/Crawley. Looks like Wunderground made some changes / updates recently as UK/Crawley returns 3 cities (previously only one, there are 2 other villages called Crawley in the UK). so I changed to UK/Pound Hill which is unique, but the error is still present.
And again if I then disable the Weather function, I get updated data even for Pound Hill which I've just amended...

**Comment by lolouk44** [comment]
Just to confirm, the issue is with my location which wunderground has changed. If I set UK/London it works.
Pound Hill is actually a more detailed location for where I am, but that doesn't appear to be recognised by SmartVISU. I guess this could be due to the space?
I tried:
UK/Pound Hill
UK/Pound-Hill
UK/Pound%20Hill
UK/PoundHill
UK/Poundhill

If I try http://api.wunderground.com/api/[API key]/conditions/q/UK/Pound%20Hill.json I get the correct xml

Any idea?

**Comment by smaiLee** [comment]
There is a similar report in German https://knx-user-forum.de/forum/supportforen/smarthome-py/1059124-neues-wunderground-plugin?p=1073904#post1073904
Wunderground has changed something and delivers multiple results if the city is not unique.
You could specify lat ond long instead of city name.

**Comment by lolouk44** [comment]
How about integrating the auto complete search in the settings page to
ensure the correct location is saved?

https://www.wunderground.com/weather/api/d/docs?d=autocomplete-api

>

**Comment by smaiLee** [comment]
You would be very welcome to implement this.

**Comment by lolouk44** [comment]
It's not that I don't want to, but my coding skills aren't probably up to the task.
This is what I was thinking about:
![wunderground_autocomplete_api_01](https://cloud.githubusercontent.com/assets/4587746/24174111/e00edb3a-0e86-11e7-94df-31ad18b89b9e.png)

Clicking on the search button will call the API:
http://autocomplete.wunderground.com/aq?query=crawley

We could use the popup function to return the name of each city:
![wunderground_autocomplete_api_02](https://cloud.githubusercontent.com/assets/4587746/24174002/61a509fe-0e86-11e7-9f97-5963a2c8a64b.png)
Clicking the city selects its correct name and format.

Side note: whenever I want to make a change to my settings, I need to apply them twice:
Change the settings, save, change them again (as they reverted to previous ones) and save again.
Not sure if it's just me

**Comment by smaiLee** [comment]
Looks nice, I will think about it.

The saving is a known bug which will be fixed in next release. Actually you don't have to save twice, just wait some seconds and reload the page. It's described in #66

**Comment by wvhn** [comment]
We set Wunderground to deprecated as there are no more free API keys available. Replacement ist weather.com.
