### ISSUE TITLE
Update example pages

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#154]
Switch deprecated widgets in example pages (like alber.eibd, fleicher, ...).

**Comment by smaiLee** [comment]
Remove some example pages as they have much redundancy

**Comment by smaiLee** [comment]
Work to do:

**all examples**
- [ ] Deliver offline values
- [ ] Replace deprecated widgets

**example1.smarthome**
- [ ] Color selector on page Büro Marco does not work

**example2.knxd**
- [ ] Remove needless tables around all shutter widgets

**example3**
- [ ] mobile view
- [ ] Example3 icons in overview (rather custom dual widget)

**Comment by wvhn** [comment]
done with pull requests #241 and #243

**Comment by wvhn** [comment]
mobile view will be kept in next develop branch. Example 3 now called "Example3.graphic".
