### ISSUE TITLE
Support for Sparkline charts

### ISSUE THREAD

**Issue by balferreira** [Martin-Gleiss/smartvisu#155]
Since we already use the highcharts, would be great if we have available Sparklines.
http://www.highcharts.com/demo/sparkline/dark-unica

**Comment by smaiLee** [comment]
If I'm right we first need a table/list widget as proposed in #93

**Comment by balferreira** [comment]
Yes, I agree with you.  But this would be a great feature too, if you wanna put a Sparkline in table.

**Comment by smaiLee** [comment]
Well, you're right. I think a dynamic sparkline could be used even in a static table.

**Comment by wvhn** [comment]
New widget plot.sparkline created with #900 . This is just a variant of plot.period with an adapted parameter set and specific chart options in the html part, using the plot.period javaScript widget code. Tables have to be set up manually.
