### ISSUE TITLE
Feature Request Turn MultimediaPicture around 180°

### ISSUE THREAD

**Issue by sandman60** [Martin-Gleiss/smartvisu#156]
Hi,

just implemented the camera picture of my Robomower and recognized that the picture was turned around 180° by mistake.

So i was searching the mode parameters within the multimedia.image widget but found nothing suitable to turn the picture, so I added an own widget by simply adding the following lines to my visu.css:

.imgFlip {
    transform: rotate(180deg);
    -ms-transform: rotate(180deg);
    -webkit-transform: rotate(180deg);
    -o-transform: rotate(180deg);
    -moz-transform: rotate(180deg);
}
Would it be possible to extend the widget with an additional option/parameter to turn the picture?

Would be great.

Cheers,
Oliver

**Comment by psilo909** [comment]
in theory, i would say, also 90° should be possible

**Comment by smaiLee** [comment]
Of course this is possible. But I'm not sure if this is really necessary.
More parameters mean more complexity, so I avoid to add parameters if they are not strongly required.

Actually you don't have to add your own widget, just use the ID prefixed by page name in your visu,css.
By the way: For current browsers you don't need the vendor-prefixed versions, you can just use transform.

```
{{ multimedia.image('myid', src, mode, time) }}
```
```
#pagename-myid {
	transform: rotate(180deg);
}
```

**Comment by wvhn** [comment]
not in general interest. The shown solution shoud be sufficient.
