### ISSUE TITLE
dynamic icons with dynamic color

### ISSUE THREAD

**Issue by WumpE78** [Martin-Gleiss/smartvisu#164]
Hi Martin, is it possible to build dynamic icons with dynamic colors?

I have Hue-Lights with brightness 0-100. This is the value for the dynamic icon.light, but nice to have is the color in rgb_r, rgb_g, rgb_b as value like rgb.colordisc!

In my solution opens a Tab the extcolordimmer widget, but for overview is brightness and color the best solution. 

thx
Stefan

**Comment by smaiLee** [comment]
Currently this is not possible.
But it's an interesting idea, I will think about an implementation.

Regards
Stefan

**Comment by smaiLee** [comment]
Possible with new basic.icon in f97b7756f733f1f7eefdee237fed2685c491312d
