### ISSUE TITLE
plot.period : multiple y-axis zero-line

### ISSUE THREAD

**Issue by lgb-this** [Martin-Gleiss/smartvisu#165]
Current delevop of Smartvisu with SmarthomeNG (dev) on a raspberry Pi3.

`{{ plot.period('',['Energie.NetzLieferung.Aktuell','Energie.Verbraucher.Geschirr'],'max','6h','',[0,'False'],[10000,'True'],'',['Einspeisen','Geschirr'],['#FF0000','#0000FF'],['spline','stair'],['','Watt','Status'],'1h',[1,2],[0,1],['#FF0000','#0000FF'],['linear','boolean']) }}`

![grafik](https://user-images.githubusercontent.com/16973456/29495004-43f67364-85b6-11e7-8dd3-b8399122898d.png)

How can i adjust the 2 y-axis on the same zero-line ?

**Comment by smaiLee** [comment]
There is no zero line on boolean axes. Boolean axes have the high state (true) in the middle of top half and the low state (false) in the middle of bottom half.
If you want the low state on bottom line use a numerical axis. But then you hardly see the line. That's the reason why I introduced the boolean axis type.

**Comment by lgb-this** [comment]
Thanks for the additional information. Case closed for me.
