### ISSUE TITLE
plot.period : ymax ignored

### ISSUE THREAD

**Issue by lgb-this** [Martin-Gleiss/smartvisu#166]
Current delevop of Smartvisu with SmarthomeNG (dev) on a raspberry Pi3.

`{{ plot.period('',['Energie.NetzLieferung.Aktuell'],'max','6h','',[0],[10000],'',['Einspeisen'],['#FF0000'],['spline'],['','Watt'],'1h',[1],[0],['#FF0000'],['linear']) }}`

![grafik](https://user-images.githubusercontent.com/16973456/29495017-8c151a1a-85b6-11e7-9601-3b13ce71135b.png)

Scale of y-axe is ok (max 10'000).

`{{ plot.period('',['Energie.NetzLieferung.Aktuell','Energie.Verbraucher.Geschirr'],'max','6h','',[0,'False'],[10000,'True'],'',['Einspeisen','Geschirr'],['#FF0000','#0000FF'],['spline','stair'],['','Watt','Status'],'1h',[1,2],[0,1],['#FF0000','#0000FF'],['linear','boolean']) }}`

![grafik](https://user-images.githubusercontent.com/16973456/29495024-b2fe2ec8-85b6-11e7-97b8-a947a760ee95.png)

Y-axe of the left system (Einspeisen, red) ymax is ignored (max. 15'000 instead of 10'000).

How can i limit the y-axe in a multi-axe-system ?

**Comment by smaiLee** [comment]
This seems to have been a bug in highcharts. After migration to version 5 in 40f30370e367b4e04325425feeb58261ebd03844 this is fixed now  (at least I couldn't reproduce it anymore).
Please check and close this issue if it's OK.

**Comment by lgb-this** [comment]
Solved. Thanks !
