### ISSUE TITLE
Configuration check on clean start page not working?

### ISSUE THREAD

**Issue by onkelandy** [Martin-Gleiss/smartvisu#168]
I've cloned both the master and develop branch, gave both directories exactly the same owner and rights. When I open the index.php page everything is fine with 2.8 - but with 2.9 it looks like, the config check is not working. I don't get checkmarks in front of the 5 list entries.

**Comment by smaiLee** [comment]
fixed by 64a70064c285655e7986fc80b0de8835e148e911
