### ISSUE TITLE
yr.no php problem to get weather

### ISSUE THREAD

**Issue by zobi** [Martin-Gleiss/smartvisu#180]
I have a problem with weather and service yr.no
I use the place : France/Champagne-Ardenne/Sedan/

Temperature are ok in my index page but some link failed.

In apache log i can see : 
` PHP Warning:  file_get_contents(http://www.yr.no/place/France%2FSedan/forecast.xml): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found\r\n in /smartvisu/lib/weather/service/yr.no.php on line 36, referer: http://192.168.2.103/smartvisu/index.php?page=config
`
the script try to get the url : http://www.yr.no/place/France%2FSedan/forecast.xml but i think the good url is : https://www.yr.no/place/France/Champagne-Ardenne/Sedan/forecast.xml 

Thanks a lot for your help

**Comment by smaiLee** [comment]
Did you use the place France/Sedan previously (w/o Champagne-Ardenne)?
I think this is some kind of caching issue.

This URL does work: http://www.yr.no/place/France%2FChampagne-Ardenne%2FSedan/forecast.xml, so the cause is neither the https nor the encoded %2F,

Try to clear the smartVISU page cache as well as your browser's cache.

**Comment by zobi** [comment]
Did you use the place France/Sedan previously (w/o Champagne-Ardenne)? => No never

yes http://www.yr.no/place/France/Champagne-Ardenne/Sedan/forecast.xml works find in Firefox
same with %2F in https or in http

i don't use page cache in smartvisu and i already try to clear cache in my browser, i also try with another browser and i have the same problem

**Comment by smaiLee** [comment]
Which version of smartVISU do you use?
Could you check the HTML-source of the weather widget an search for the URL there.
And in the network tab of the developer tools of your browser you can find a call to lib/weather/service/yr.no.php - can you post its request url please.

**Comment by zobi** [comment]
I'm using the last version fresh upgrade with github
in the source file i've found this :  $url = 'http://www.yr.no/place/'.rawurlencode($this->location).'/forecast.xml'; is this what you are looking for ?
the network tab filter by "weather" :
![weather bug](https://user-images.githubusercontent.com/1262594/34574194-fafc3d7e-f176-11e7-9a44-c5a155ae9f79.PNG)

**Comment by smaiLee** [comment]
The wrong request is on second line of network tab. So the question is, where this comes from.
Did you perhaps specify this location in the widget call?

**Comment by zobi** [comment]
hoooooooo very very sorry ....
after check my page i called : 

` {% import "clock.html" as clock %}
        {{ clock.digiclock('clock','France/Sedan') }}
`

i didn't think that clock use yr.no ! 
i just replace with : 

` {% import "clock.html" as clock %}
        {{ clock.digiclock('clock','France/Champagne-Ardenne/Sedan') }}
`
and it works now ! 

Thanks a lot and sorry for my mistake
