### ISSUE TITLE
App crashing on both iPad and iPhone 

### ISSUE THREAD

**Issue by influx-bonobo** [Martin-Gleiss/smartvisu#183]
https://secure.helpscout.net/conversation/500104569/11773/?folderId=520784

**Comment by smaiLee** [comment]
Spam? The link leads to a login page.

**Comment by msinn** [comment]
Might be advertising for the help platform helpscout.net.

If it has anything to do with smartVISU (what I don't believe since smartVISU has no ios App) the poster should post the information here.
