### ISSUE TITLE
Optimize Template Checker

### ISSUE THREAD

**Issue by onkelandy** [Martin-Gleiss/smartvisu#186]
Aktuell ist im Template Checker tatsächlich weder die Möglichkeit für mehrere Typen noch für Arrays mit unterschiedlichen Typen vorhanden. 

Wäre schön, wenn es einen Check für zB folgende Varianten gäbe:
Entweder text(quad, main) ODER Array [quad/main, num/int/bool]
Einzelnes Item ODER Array mit verschiedenen Attributen, die für plot.period erlaubt sind.

**Comment by wvhn** [comment]
plot and uzsu parameter check introduced with #870
