### ISSUE TITLE
Periodical refresh of multimedia.slideshow

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#188]
Add parameter for refresh time to multimedia.slideshow to re-scan directory for new/removed images.

(see https://knx-user-forum.de/forum/supportforen/smartvisu/1148881-last-call-für-flug-sv-2-9?p=1178081#post1178081)

**Comment by wvhn** [comment]
should maybe be done by clearing cache and page reload, since complete directory is read into an array in Twig/html and thus is static.

**Comment by Bonze255** [comment]
I think it could be moved into the js ?

**Comment by wvhn** [comment]
cyclic directory read by new php service "./lib/getdir.php". Ajax request gets the file properties into js. Changes get effective on the fly with the selected refresh duration (default: 1d).

Solved with #521
