### ISSUE TITLE
device.shutter dont create GAD

### ISSUE THREAD

**Issue by flipkill1985** [Martin-Gleiss/smartvisu#191]
Hello,

In Develop device.shutter did not creat a GAD in FHEM (Fronthem)

best regards Jan

**Comment by smaiLee** [comment]
Which driver did you use?
Do other widgets than device.shutter work?
FHEM driver does not work at all in develop afaik, use Domotiga instead.

**Comment by smaiLee** [comment]
@flipkill1985 does the fix work an can de issue be closed?

**Comment by smaiLee** [comment]
Closed due to no response.
