### ISSUE TITLE
dropins folder for the page

### ISSUE THREAD

**Issue by hcs-svn** [Martin-Gleiss/smartvisu#198]
For files, that are not widgets, it would be nice to have a "dropins" folder located in the page where we can put .js files for auto load.

One reason is, that I would like to put the optional FHEM-addon-driver (that is individual for a page) into the page and not into the installation.
Some other .js files, that are page related, would also fit into this folder.

Tested it with the page/widgets folder where it works but that's not the right place for such files.

**Comment by smaiLee** [comment]
This does already exist for some time (even longer than dropins):
Any .js file in yourpages/js/ and any .css in yourpages/css/ gets imported (and additionally visu.js and visu.css in yourpages/).

**Comment by hcs-svn** [comment]
Thanks, knew only page/visu.js.
page/js works as expected.
