### ISSUE TITLE
Autorefresh von Weather u. Telefonwidget

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Martin-Gleiss/smartvisu#20]
```
wie im Titel schon angegeben, sollen sich die beiden Widgets
automatisch akualisieren (nicht nur beim Seitenreload)



```

Original issue reported on code.google.com by `martin.z...@gmail.com` on 9 May 2013 at 6:10

**Comment by smaiLee** [comment]
implemented by @lbernau in commit 33c28c9ec40655f3005ede9a49412f4cde71a624
