### ISSUE TITLE
Blocks alignment fail?

### ISSUE THREAD

**Issue by kr2** [Martin-Gleiss/smartvisu#201]
![unbenannt](https://user-images.githubusercontent.com/1094983/38198719-3760b5d6-368e-11e8-8834-15ce915dbe17.jpg)

**Comment by smaiLee** [comment]
Which version (2.8 or develop)?
Which Browser?

**Comment by kr2** [comment]
Google Chrome | 65.0.3325.181

current develop c1df60baec55499834b99f8076f87f5ba9c7db96

[this](http://docu.smartvisu.de/2.8/index.php?page=design/design_block) works fine

**Comment by smaiLee** [comment]
Strange: I can reproduce it in Firefox 59 but not in Google Chrome.
I did already know about such problems in FF. There seems to be some rounding problem on *em* calculations.
I will soon commit a workaround which hopefully works on all browsers.

**Comment by kr2** [comment]
I tried the current version (668910211469a2cfabd4d7cb0f4fc828f6726f21), but there was no improvement.
For me it is the same in Firefox, Edge and Chrome. All of them show the "void".

Could it be a problem with my server setup? (Everything else works fine.)

**Comment by smaiLee** [comment]
The server is not the problem, this is an HTML rendering issue.
Did you clear the cache in smartVISU and your browsers (or press ctrl+F5)?

**Comment by kr2** [comment]
Yes, I tried both.

**Comment by smaiLee** [comment]
That's weird.
Do you have any custom styles (e.g. in visu.css)?
Please check if pages/base/base.css is the current version.

**Comment by kr2** [comment]
The misalignment happens if the block is overfilled (tested in Firefox and Chrome). I added a test page (Test.zip) for the page folder.

![image](https://user-images.githubusercontent.com/1094983/38499792-f258cd22-3c08-11e8-9254-049617507d14.png)
[Test.zip](https://github.com/Martin-Gleiss/smartvisu/files/1890014/Test.zip)
