### ISSUE TITLE
Rotes Error-Dreieck automatisch entfernen

### ISSUE THREAD

**Issue by msinn** [Martin-Gleiss/smartvisu#206]
Ich habe ein kleines Thema mit Wunderground. In letzter Zeit failed immer mal wieder ein Request, was zu dem roten Dreieck oben rechts führt.
So weit so gut. Wenn im folgenden die Anfragen von Wunderground wieder beantwortet werden, bleibt das rote Dreieck. Könnte das nicht automatisch wieder verschwinden (wie beim smathome.py Treiber)?

smaiLee:
> Guter Punkt. Kannst du einen Issue dazu eröffnen? Das müsste prinzipiell für alle Services und Treiber implementiert werden, deshalb ist es wohl eher etwas für später.

**Comment by wvhn** [comment]
phone and weather widgets now store similar errors only once. Errors are deleted automatically if services work correctly again.
See #500
