### ISSUE TITLE
Eigene Icons für den Waste Kalender

### ISSUE THREAD

**Issue by stars112** [Martin-Gleiss/smartvisu#219]
Im Müllkalender sollte es möglich sein, eigene Icons für andere Events als die normale Müllabfuhr darzustellen.

Workarround von Chris46:
Man füge unter /widget/calendar.js vor "entry.icon = "icons/ws/message_garbage_2.svg";" in Zeile 173 folgendes ein: if(!entry.icon || entry.icon === "message_garbage")

Sieht dann so aus:
Code:

if(!entry.icon || entry.icon === "message_garbage")
    entry.icon = "icons/ws/message_garbage_2.svg";

Jetzt ist es möglich in der custom.ini bspw. dies einzutragen:
Code:

[calendar_event_format]
Weihnachtsbaum Abholung[icon] = icons/ws/light_x-mas_tree.svg

Wichtig ist, dass der Pfad zu dem icon angegeben wird.

Ein Icon dazu in dem passenden Format wurde erstellt und kann in diesem Zusammenhang benutzt werden.

**Comment by wvhn** [comment]
should have been autoclosed with release of v2.9.2
