### ISSUE TITLE
Rotes Error-Dreieck kann mehrere smarthome Fehler aufnehmen und wird dann nicht komplett automatisch gelöscht

### ISSUE THREAD

**Issue by stars112** [Martin-Gleiss/smartvisu#220]
Die Error Meldung wird von mehreren gleichen Fehlern getriggert. Nach dem der Fehler beseitigt ist, wird nur der letzte Fehler zurückgesetzt und nicht die ganze Liste von dem gleichen Fehler.
Das rote Dreieck "Error" bleibt also stehen und die restlichen Meldungen müssen einzeln quittiert werden.

**Comment by wvhn** [comment]
phone and weather widgets now store similar errors only once. Errors are deleted automatically if services work correctly again.
See #500
