### ISSUE TITLE
Smartvisu IOBroker und RP3b+

### ISSUE THREAD

**Issue by YuriBiermanov** [Martin-Gleiss/smartvisu#224]
Hallo,

ich bin schon länger auf der Suche nach einer Installation dieser Visu für einem Raspberry und bin über das IOBroker-Forum hierher gelangt. ist dieses Repository für IOBroker auf einem Raspberry geeignet?, Falls die Hardware unzureichend ist, auf welcher kann ich dieses Frontend laufen lassen? Ich finde dieses Frontend sehr schön und möchte es sehr gerne nutzen, daher die Frage.

Gruß,
Jürgen

**Comment by smaiLee** [comment]
Die Hardwareanforderungen im Betrieb sind sehr gering, ein Raspberry reicht also.
Es fallen mir nur zwei Stellen ein, die etwas mehr Leistung brauchen und damit auf einem kleineren Raspberry spürbar länger dauern.
Die eine ist, wenn man den Cache aktiviert hat und diesen leert (etwa nach einer Änderung), dann werden beim ersten Aufruf die Dateien neu gebildet. Dafür läuft es danach auf schwacher Hardware deutlich schneller als ohne Cache.
Die andere liegt beim Kalenderservice, speziell bei Abruf von grossen ICS-Dateien. Diese werden auf dem Server verarbeitet. Weil ICS keine Sortierung der Termine vorgibt, muss die Datei komplett geparsed werden, selbst wenn zuletzt nur ein Termin angezeigt wird.

**Comment by YuriBiermanov** [comment]
ich versuche schon länger diesen Adapter auf meinem Raspberry über ssh und der Weboberfläche von IOBroker zu installieren, allerdings schaffe ich es bis jetzt leider nicht.

Was muss ich denn machen, um diesen Adapter geladen und später installiert zu bekommen? 
Ich arbeite schon etwas länger mit dem Raspberry, aber das übersteigt meine dürftigen Fähigkeiten ;-)

**Comment by smaiLee** [comment]
Da kann ich leider nicht weiterhelfen, weil ich IOBroker nur rudimentär kenne. Im [ioBroker Forum](https://forum.iobroker.net/) dürftest du eher Antworten dazu finden.
