### ISSUE TITLE
Datum wird gecached?

### ISSUE THREAD

**Issue by Fareroo7** [Martin-Gleiss/smartvisu#226]
Ich bin seit kurzen auf Version 2.9 umgestiegen und seit dem habe ich ein Problem mit dem Datum.
Es wird nicht aktualisiert.
Kann es sein, dass das Datum (smartdate Twig-Funktion) gecached wird?
Sobald ich den Cache leere wird das Datum auf den aktuellen Tag gestetzt.

Aus dem ( [Changelog](https://github.com/Martin-Gleiss/smartvisu/blob/develop/changelog.md#improvements) geht hervor, das in Version 2.9 etwas am cache geändert wurde.

Villeicht liegt hier das Problem?

**Comment by smaiLee** [comment]
Wahrscheinlich verwendest du eine Kopie der alten base.html. In 2.8 war da die Uhrzeit fix im HTML,
Im [develop Branch](https://github.com/Martin-Gleiss/smartvisu/blob/258395f580c4dbfccf3af1b778e3dc2b85a49653/pages/base/base.html#L23) wird da das Widget `clock.miniclock` verwendet, welches die Zeit nicht cached und auch die Einstellung zu Server- oder Clientzeit berücksichtigt.

**Comment by Fareroo7** [comment]
Danke!
Genau das war mein Fehler.
Funktioniert alles wieder wie es soll.
