### ISSUE TITLE
icon.zenith bug

### ISSUE THREAD

**Issue by WumpE78** [Martin-Gleiss/smartvisu#228]
Hi everyone,

i have a bug in icon.zenith. 

i have this icon, with a resolution 0-255 digits in the weather-widget darksky and yr.no implemented.
Firefox / Chrome and iE crashes 2 times per Day. When i uncomment the icon.zenith -line and show only a img every works fine. 

**code in weather.html (icon.html is imported)**
```

<div style="line-height:18px; margin-top:-16px; font-size: 14px;">
<span class="sunrise" style="vertical-align:bottom;"></span>
/**{{ icon.zenith('daytime_icon', '', 'FH_AA_DAYTIME_SUN.state') }}**/
<img class="icon" src="{{ icon0 }}weather_sunrise.svg" style="width:40px; margin-bottom:-6px;"/>
<span class="sunset" style="vertical-align:bottom;"></span>
</div>


```
class sunrise and sunset is modified in weather.js and weather-service php-file

**Comment by wvhn** [comment]
@WumpE78 
I have "inherited" the maintainers task in early 2020. Never saw this bug before. Is it still showing up and do you have a chance to catch the conditions under which the crashes appear? 

BR
Wolfram

**Comment by wvhn** [comment]
no further hint that this might be faulty
