### ISSUE TITLE
Update Check -> https und MAC/VISU-Adresse?

### ISSUE THREAD

**Issue by ThomasCr** [Martin-Gleiss/smartvisu#235]
Hi,
mir ist eben im Webserver Protokoll folgender Fehler untergekommen:

> PHP Warning:  file_get_contents(http://smartvisu.de/download/check.php?local=2.9&amp;hash=XXXXXXX): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error\r\n in /var/www/html/smartVISU-dev/lib/base/check_update.php on line 26\n'

Ich vermute, die Prüfung sollte auf https umgestellt werden. Weiterhin verstehe ich nicht, für was der Hash unserer MAC-Adresse übermittelt werden soll, im Fehlerfall auch noch die Adresse der Visu?! Auch noch in MD5, was man eigentlich einfach per Brute-Force zurück bekommen kann.

Noch zusätzlich, ist es auf vielen Systemen nicht mal eth0, weswegen er dann auch oft auf den Fehlerfall ausweicht und immer die URL und mehr der Visu übermittelt.

Ich bin ehrlich gesagt nicht ganz damit einverstanden und verstehe auch nicht wieso man das Braucht?

Warum hat man nicht einfach eine GUID pro Setup generiert, was in der config.php hinterlegt ist. Diese kann man dann ja an den "Updateserver" weitergeben. Aber nicht Brisante Details über das System - DSGVO lässt grüßen ;-)

Das ganze wurde wohl hier eingeführt: bb673be30251762e87d447e06beb0c7b078146cb

**Comment by smaiLee** [comment]
Da smartvisu.de nicht von mir betrieben wird und dies vor meiner Zeit implementiert wurde, müsste dazu @Martin-Gleiss Stellung nehmen.

**Comment by psilo909** [comment]
Kurzfristige Lösung: einfach bei sich selber ausbauen ;) läuft bei mir schon seit Ewigkeiten

**Comment by smaiLee** [comment]
Ich habe den Hash entfernt. Dadurch antwortet smartvisu.de auch nicht mehr mit Status 500.
Ausserdem kann man die Updatesuche nun in der Konfiguration deaktivieren.

**Comment by psilo909** [comment]
@smaiLee danke!!! nachdem "der Kollege" seit Monaten wieder in der Versenkung verschwunden ist, finde ich, dass wir dazu irgendwo auch das Recht haben...
