### ISSUE TITLE
basic.print: Colorizing sometimes not working as expected

### ISSUE THREAD

**Issue by Tom-Bom-badil** [Martin-Gleiss/smartvisu#237]
>{{
>   basic.print('', 'heizung.sensoren.af1', '%d °C', '',
>   [-15,15,25], ['blue','lightblue','green','orange'])
>}}

This has been working well during summertime, and still is for values of 10°C and above:
![image](https://user-images.githubusercontent.com/20954551/68991547-2cd10580-0860-11ea-9652-8f2a7a8db6f9.png)

As soon temperature goes down to 9°C and below, the color is displayed in orange instead of light blue:
![image](https://user-images.githubusercontent.com/20954551/68991563-58ec8680-0860-11ea-8f77-f82fa672229d.png)

The effect is reproducable, not just a one-time error. There is also a second item with 3 thresholds and the same strange effect. All other basic.print's with just 2 thresholds are working fine and as expected.

**Comment by Tom-Bom-badil** [comment]
Possibly found the reason for this behaviour.

This only seems to happen if the source item of the value contains digits (like the yellow 7°C above - the corresponding shNG item held actually the value **7.2** at the time of reading). The item itself is correctly defined as 'num'.

@smaiLee: Is it possible that the comparison doesn't recognise numbers with digits and is using strings when it find a '.' ? This would explain why the item turns yellow at 9°C, because in string comparison '9.9' > '25' (see threshold definition in the first post).

Also, this would explain why the color turns back to light blue again at below 2°C, because with strings '1.9' < '15', and '2.0' > '15' (=still yellow) ...

/tom

**Comment by smaiLee** [comment]
Unfortunately I can't reproduce this issue.
Your theory sounds reasonable, but I can't confirm it. When both, the threshold an the received value (after applying the formula but before formatting) are numeric, then they are compared as numbers:
https://github.com/Martin-Gleiss/smartvisu/blob/1bc37f3227f96034ee2ee660e8b73708ae2cd1f4/widgets/basic.js#L761

**Comment by Tom-Bom-badil** [comment]
Found the cause. If a format is added to a num value, the whole thing is considered as a string. At 7.3 °C outside right now, I am getting the following results:

`{{ basic.print('', 'heizung.sensoren.af1', '%d °C', '', [0,15,25], ['blue','lightblue','green','orange']) }}`
Results in an orange-colored 7°C (erratic behaviour). The string "7 °C" is used for comparison.

`{{ basic.print('', 'heizung.sensoren.af1', '', '', [0,15,25], ['blue','lightblue','green','orange']) }}`
Results in a light-blue colored 7.1 (expected behaviour). The num 7.1 is used for comparison.

Seems I can only work around this with helper items that do a proper rounding for each temperature (having a lot of them meanwhile).

/tom

**Comment by Tom-Bom-badil** [comment]
For some odd reason, it seems that I was running on an elder version of basic.js, compared to the one quoted by @smaiLee above. No clue why.

After replacing it with the latest develop version, quite some code in threshold comparison has changed, and an additional/new variable 'value' is used for comparison (insted of the variable 'calc' in the elder version). So, in the develop, the issue seems to be fixed, and comparison is working properly, even along with formats:

Example for 9° outside:

`{{ basic.print('', 'heizung.sensoren.af1', '°C', 'Math.round(VAR)', [0,15,25], ['blue','lightblue','green','orange']) }}`

Result is now light blue, as expected:

![image](https://user-images.githubusercontent.com/20954551/71414397-108e6880-2657-11ea-81df-34373a289e1b.png)

Issue closed, apologies for the confusion.

/tom
