### ISSUE TITLE
Provide a status item to show status of stateswitch, dimmer, etc.

### ISSUE THREAD

**Issue by onkelandy** [Martin-Gleiss/smartvisu#297]
In smarthomeNG the item value changes instantly without waiting for an answer. E.g. if you change the value of a KNX switch, the specific item gets updated immediately and might then later on be overwritten by a response from the KNX bus.

In general it would be possible to create a child item of the switch with just the status address - but smartvisu would need to support this extra item to update the status of the shown icon/text. 

Generally speaking we'd need something like this:
```
{{ basic.stateswitch(id, item, type, value, icon, text, color, indicator, item_longpress, value_longpress, value_longrelease, response_item) }}
```
where the last attribute is responsible for the visual feedback on the stateswitch (color, icon change, etc.)

**Comment by wvhn** [comment]
Would it be sufficient to just send the changed value on the websocket without immediate internal update in SV and then wait for the backend to send the update? So smartVISU would still send and listen to the same item while the backend is able to use different send and listen addresses for an item, anyway. 
I think this should work with smarthomeNG but I'm not sure about the other backends.

**Comment by wvhn** [comment]
Giving it a try is easier than I thought. You just need to disable widget.update in the function io.write by commenting it out in ./driver/io_smarthomeng.js:
```
write: function (item, val) {
   io.send({'cmd': 'item', 'id': item, 'val': val});
  //widget.update(item, val);
},
```
The update then comes with the answer from the backend.

We could make the immediate update a configurable option.

**Comment by onkelandy** [comment]
This sounds very promising! An option for that in the settings would be a good solution.

**Comment by wvhn** [comment]
done with #901 
We introduce a combined item formatted "item_status:item_control". A  colon separates the two items. smartVISU subscribes updates for "item_status" and sends commands to "item_control".
