### ISSUE TITLE
Optimize Template Checker - Widget Deprectation Check

### ISSUE THREAD

**Issue by iamathome** [Martin-Gleiss/smartvisu#300]
Within the Widget Deprectation Check the replacement code proposal looses necessary quote marks. For example

Parameters: 'AussentemperaturD', 'Zentral.Wetterdaten.Aussentemperatur', '°C'

As a workaround it would be ok to inform the user about this behavior. 

R
<img width="861" alt="Bildschirmfoto 2020-03-23 um 21 18 16" src="https://user-images.githubusercontent.com/62755927/77765925-3c96fc80-703f-11ea-95ce-96900978e70d.png">
eplacement: {{ basic.print(AussentemperaturD, Zentral.Wetterdaten.Aussentemperatur, °C) }}

**Comment by wvhn** [comment]
has been fixed by introducing a new class for removed widgets and modifying the replacement strings in deprecated widgets
