### ISSUE TITLE
Some widgets are not correctly validated on W3 validator

### ISSUE THREAD

**Issue by onkelandy** [Martin-Gleiss/smartvisu#304]
Some widgets contain attributes not allowed by HTML standards, e.g. "<input orientation=".." handle="..">
They should be renamed to data-orientation, etc. in the HTML and JS files.
Some img don't have alt attributes

**Comment by wvhn** [comment]
Checks have been performed on all docu pages and widgets. Corrections have been implemented with #522  .

Open Point: some unknown attributes mainly in multimedia widgets (e.g. "stoptimer", "timer" ...). The widgets work fine but of course the attributes can not be interpreted by the browser.
