### ISSUE TITLE
Integrate "Toast" as alert message

### ISSUE THREAD

**Issue by wvhn** [Martin-Gleiss/smartvisu#309]
https://kamranahmed.info/toast

Could be a widget reacting on changes in a  definable watch item ...
Ideas welcome

**Comment by Bonze255** [comment]
first version could by tested https://github.com/Bonze255/smartvisu_widgets/tree/master/toast

**Comment by wvhn** [comment]
@Bonze255 great Job
The widget has been mergerd with PR #430
