### ISSUE TITLE
Korrektur Anzeigeformat  in lang/de.ini

### ISSUE THREAD

**Issue by Bonze255** [Martin-Gleiss/smartvisu#346]
in der de.ini, werden die format des print widgets definiert, 
wird  sowas geschrieben 

`{{` basic.print('env.location.sun_position.elevation', 'env.location.sun_position.elevation.degrees','°') }}

bekommt man das hier in der Visu  H: 305,2 °C

deshalb muss  **° = "%01,1f °C"** durch 

```
 ° = "%01,1f °"
 °C = "%01,1f °C"
```
ersetzt werden.

**Comment by wvhn** [comment]
closed w/ #357
