### ISSUE TITLE
Config Page: Port 2424 for SmarthomeNG should NOT be set

### ISSUE THREAD

**Issue by onkelandy** [Martin-Gleiss/smartvisu#350]
right now when switching to smarthomng as a driver the port automatically gets populated with "2424". That should stay empty as for reverse proxy the field HAS to stay empty.

**Comment by wvhn** [comment]
I would prefer providing a configuration switch for reverse proxy which then actively deletes the port number in the config_data.  So we could leave the port number preset to 2424 for plain smarthomeNG installations which the less experienced users will appreciate.

**Comment by wvhn** [comment]
closed with pr #358
