### ISSUE TITLE
Secure WebSocket Option

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Martin-Gleiss/smartvisu#37]
```
Per Config Datei festlegen, ob WebSocket oder WebSocket Secure verwendet werden 
soll. Der diff setzt dies nur für io_smarthome.py um. io_eibd, io_json, 
io_linknx und io_offline nutzen keinen WebSocket. Eventuell kann dies noch für 
io_domotika umgesetzt werden.
```

Original issue reported on code.google.com by `sven.sch...@gmail.com` on 12 Feb 2015 at 6:56

Attachments:
- [SmartHome_WebSocket_Secure.diff](https://storage.googleapis.com/google-code-attachments/smartvisu/issue-37/comment-0/SmartHome_WebSocket_Secure.diff)

**Comment by ReneHezser** [comment]
Good work. I was thinking about implementing this feature. But with your work, I think about implementing Authentication.

**Comment by ThomasCr** [comment]
I am too have some ideas how to implement the auth and a auth interface for sh.py.

**Comment by geertge** [comment]
Hi, how to implement secure websocket on smartvisuNG? Is this available trough a upgrade?

Thanks,

Geert

**Comment by smaiLee** [comment]
obsoleted by #135
