### ISSUE TITLE
Merge request: New caldav calendar service

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Martin-Gleiss/smartvisu#39]
```
New caldav based calendar service.
Tested with owncloud 8.0.2
```

https://github.com/willjoha/smartvisu/commit/3162f0a413493e699c1fec732edfc64ee772259c

Original issue reported on code.google.com by `willj...@gmail.com` on 8 Apr 2015 at 8:18

**Comment by smaiLee** [comment]
integrated in bc3ed7a9bb9d0dbe7c845020c073678326c9a77b
