### ISSUE TITLE
Allow usage of location id for openwheatermap

### ISSUE THREAD

**Issue by DengelFred** [Martin-Gleiss/smartvisu#429]
Hello,
It would be great if the plugin supports the location id in order to avoid trouble with duplicate city names.

Idea:
Check if the location is numeric only. In this case call the API with the "id=" parameter instead of "q=".

Edit: Maybe the plugin can use directly the coordinates (lat, lon) from shNG (if available?)

Best regards, Thomas

**Comment by wvhn** [comment]
Location can now be entered in the following ways:
	* use latitude and longitude of your location e.g. `lat=50.93331&lon=6.95`
	* use the city ID provided by openweathermap.org e.g. `id=2886242`
	* use the ZIP code of your location, e.g. `zip=50667,DE`
	* use the city name e.g. `Köln,DE`

closed with #527
