### ISSUE TITLE
Error in widget.explode()

### ISSUE THREAD

**Issue by orttech** [Martin-Gleiss/smartvisu#437]
explode changes the order of items in list. This is critical for such widgets, like comfortchart. 
Example : {{ plot.comfortchart('c1','13','12') }}
In this case humidity and temp will be swapped, because explode() makes a kind of sorting.
Proper implementation:

```
	explode: function (text) {
		var ret = Array();
		var unique = Array();

		// More than one item?
		if (text.indexOf(',') >= 0) {
			var parts = text.explode();

			for (var i = 0; i < parts.length; i++) {
				if(!ret.includes(parts[i]))	ret.push(parts[i]);
			}
		}
		else if (text.trim() != '') { // One item
			ret.push(text.trim());
		}

		return ret;
	},
```

**Comment by wvhn** [comment]
Thanks for the contrubtion. 
The problem occurs only with purely numeric item names which are not allowed in most of the supported backends.
Nevertheless I push the change with an important modification which excludes empty strings from being transferred.

`if(!ret.includes(parts[i]) && parts[i] != '' )	ret.push(parts[i]);	`

Closed with #438
