### ISSUE TITLE
Problem with Fritzbox TR-064

### ISSUE THREAD

**Issue by orttech** [Martin-Gleiss/smartvisu#439]
Readout of the call list doesn't work. Reports:

_PHP Warning:  stream_context_create(): options should have the form [&quot;wrappername&quot;][&quot;optionname&quot;] = $value in lib\phone\service\fritz!box_TR-064.php on line 136_

Changing to   `$GetCallListXml = file_get_contents($url, false, null);` has solved the problem, but is probabely not intended.

**Comment by jentz1986** [comment]
I had the same error on my Synology when using PHP 5.6. With PHP 7.0 and up this is gone...

**Comment by wvhn** [comment]
`$GetCallListXml = file_get_contents($url, false, stream_context_create(array('http://' => array('ssl' => $self->context_ssl))));`
solves the problem as well. 
On my Raspberry the code works well without the change. Under Windows with XAMPP Apache Server, I see the same issue. Both are using php >7.3.
I leave the issue open until further tests results are available

**Comment by wvhn** [comment]
The new solution works fine also on Raspberry.

Additionally I have changed the output of the phone service. On outgoing calls, the called number is being displayed now instead of the users number.

PR will follow.

**Comment by wvhn** [comment]
PR is #444
