### ISSUE TITLE
Dynamic in basic.switch not working

### ISSUE THREAD

**Issue by copystring** [Martin-Gleiss/smartvisu#468]
With 3.0 I think I found a bug:

`{{ basic.stateswitch('', 'switch.eingangslicht', '', '', [icon.light('','','switch.eingangslicht'), icon.light('','','switch.eingangslicht')], 'Eingangslicht') }}`
results in this: 
![image](https://user-images.githubusercontent.com/1298861/106338372-eebcd780-6293-11eb-8a8c-d7d7d001c610.png)

Looking at the html code the bulb is there but it is all hidden:
![image](https://user-images.githubusercontent.com/1298861/106338476-32afdc80-6294-11eb-9052-3746dacfa3bc.png)

`{{ icon.light('','','switch.eingangslicht') }}` on is it's own works just fine. See the screenshot to the right of the red box.

Or is this not a bug and I have to change something?

**Comment by wvhn** [comment]
The problem is not the icon but the text.  If you leave  the text empty, the icons work fine.
I’ll do a fix ASAP.

**Comment by wvhn** [comment]
closed with #472 
Thanks for a quick test.
