### ISSUE TITLE
Improve basic.multistate - additional parameter (array) to colorize symbols

### ISSUE THREAD

**Issue by ddtlabs** [Martin-Gleiss/smartvisu#49]
perhaps in the form: {{ basic.multistate(id, item, val, img, type, color) }} like other basic widgets.

**Comment by ddtlabs** [comment]
I missed that other basic widgets do not have these option in the current branch, too.
Please see:
http://knx-user-forum.de/forum/supportforen/smartvisu/31400-umstellung-der-icons-auf-svgs?p=833931#post833931
http://knx-user-forum.de/forum/supportforen/smartvisu/31400-umstellung-der-icons-auf-svgs?p=835986#post835986

/Uli

**Comment by smaiLee** [comment]
superseded by #83
