### ISSUE TITLE
Faulty behavior with IOS 9.x -10.x

### ISSUE THREAD

**Issue by ddtlabs** [Martin-Gleiss/smartvisu#52]
Dear Martin,

there are some problems in conjuction with smartvisu and Apples IOS 9.x:
- Wrong page will be displayed after closing a popup. Can be fixed within popup's <div> with data-history="false".
- But nevertheless after closing the popup then the page is unusable because no element reacts anymore and the page is cut at bottom (you cannot scroll).
- All pages are displayed _under_ apple's info head line. With previous IOS versions pages started at the top of the sceen and apple's info header line was transparently visible.
  The first 2 problems appear in fullscreen mode and in normal browser mode with Safari and other browsers.
  If there are any questions don't hesitate to ask me.

Kind regards,
Uli

**Comment by ddtlabs** [comment]
I do not want to annoy but has smartvisu development been stoped? No reaction or comment over 3 weeks.
Btw: IOS 9.1 release version did not change anything in this faulty behavior.

**Comment by Martin-Gleiss** [comment]
No, it is not been stopped. We will integrate this in v2.8.

**Comment by ddtlabs** [comment]
Thank you for your answer. Is there already a rough schedule for releasing 2.8?

**Comment by tuxedo0801** [comment]
It's now 08/2016 ... and this is the last open issue for 2.8 (which is now about 10 months old).

Any progress on this?

**Comment by smaiLee** [comment]
As far as I know the only reliable solution is an upgrade of jQuery mobile to Version 1.4.
I'm working on this, but there are quite a lot of adaptions required.

Despite I'm getting on well, this will not be part of release 2.8, which is desired to be published as soon as possible.
Especially because of the testing on several platforms which will be badly needed. And I can't do this all by myself.

Did you test if this still exists on iOS 9.2? As one can read on the Web some issues were gone with 9.2.

**Comment by ddtlabs** [comment]
The issues described in the first post still exists on my iPad mini running with IOS 9.2.3. The same smartVISU installation is running fine with IOS 8.x

**Comment by mircoby** [comment]
Using Smartvisu 2.8 with following restrictions:
iOS 9.1 (iPad 3) and iOS 10.1.1. (IPadPro / Iphone 6s) doesn´t display graphs when Page is opened by a desktop shortcut. It is working when the url is directly typed into Safari browser.
With iOS 10.2. plots are displayed. First time opening, plots are running over the boarders, reload of page fixes the issue, correct behaviour.
Alternative workaround for wrong scaled plots is the sleep(1) operation in widget_dbplot.php as described here: https://forum.fhem.de/index.php/topic,43134.msg543316.html#msg543316

**Comment by smaiLee** [comment]
dbPlot widgets aren't part of smartVISU. Does this also apply for plot.* widgets?

The problem with desktop/homescreen icons might be the cache. As far as I read resources like JavaScript of homescreen apps get cached and can't be refreshed easily.

**Comment by mircoby** [comment]
Tried out plot.comfortchart, this is working correctly also with iOS9.1
Source of dBPlot you can find here: https://github.com/ToGe3688/db_plot_widget

**Comment by smaiLee** [comment]
I don't see anything wrong in dbPlot source.
Perhaps the pagecreate event is too soon as the elements aren't shown in browser then.

Sorry, I can not support more on foreign code, please contact the developer of dbPlot. This does not seem to be a problem of smartVISU itself.

**Comment by smaiLee** [comment]
Can anyone with iOS device check if the update of jQuery Mobile in bf16fdac3d0eec535ef6296c515799de7a00aaa6 did solve this problems please?

**Comment by smaiLee** [comment]
@ddtlabs could you check if the issues are fixed in develop branch so we can close the issue?

**Comment by smaiLee** [comment]
Seems to work now, tested by @msinn, @Foxi352 and @Tom-Bom-badil
