### ISSUE TITLE
No Button to grab on slider

### ISSUE THREAD

**Issue by Dlay2017** [Martin-Gleiss/smartvisu#532]
With the update to v3.1.0 my sliders are empty. The little knob on the slider is missing. 
I followed exactly the upgrade description.

![image](https://user-images.githubusercontent.com/26193050/118504495-daf68d80-b72b-11eb-824c-8e0820dba21c.png)

**Comment by Dlay2017** [comment]
This appears also when viewing the documentation:

![image](https://user-images.githubusercontent.com/26193050/118515359-9bcd3a00-b735-11eb-91aa-942759af137f.png)

**Comment by wvhn** [comment]
Please clear the cache in smartVISU config page and the browser history (or website data of smartVISU e.g. on iPad). If this still doesn't help, delete the folders "twigcache" and "pagecache" in ./temp directory, manually.

**Comment by Dlay2017** [comment]
Thanks, that solved the problem.
