### ISSUE TITLE
No GADs sent to fhem when using Plots

### ISSUE THREAD

**Issue by Dlay2017** [Martin-Gleiss/smartvisu#533]
If have created a plot in SV3.1.0 but plot.rtr rather than plot.period create a GAD in fronthem 

Regardless of what i try to do, they are not listed.

**Comment by wvhn** [comment]
This seems to be a problem in fronthem, not in smartVISU: https://forum.fhem.de/index.php/topic,86584.0.html

**Comment by Dlay2017** [comment]
The problem can be solved by using the fronthem files in the first post here --> [https://forum.fhem.de/index.php/topic,86584.0.html](https://forum.fhem.de/index.php/topic,86584.0.html)

Afterwards block any updates of fronthem in fhem with

`attr global exclude_from_update 01_fronthem.pm 31_fronthemDevice.pm fronthemEditor.js 99_fronthemUtils.pm`
