### ISSUE TITLE
smartVISU image und RPI2

### ISSUE THREAD

**Issue by hellobello** [Martin-Gleiss/smartvisu#56]
Hallo liebe Entwickler, ich wollte gerade die software ausprobieren, aber ich glaube das Image zum downloaden ist nicht für den Raspberry Pi 2 B geeignet. Der macht nämlich beim booten genau gar nichts. Ich habe mehrere SD Karten ausprobiert. Per NOOBS habe ich dann Raspbian aufgespielt, da bootet der Pi ganz normal. Jetzt versuche ich gerade händisch den ganzen [ironie] Klatteratatsch [/ironie] zu installieren, nach Anleitung auf 

https://github.com/mknx/smarthome/wiki/Komplettanleitung-Installation-sh.py-,-smartVISU,-eibd-und-1-Wire 

und hänge hier bei der USB-KNX Schnittstelle :-(
kann mir bitte jemand bestätigen dass der RPI2 das Image nicht mag? Sonst zweifle ich an meinen nicht vorhandenen Fähigkeiten.

Beste Grüße, Michael

**Comment by macflei** [comment]
Richtig, das Image auf smartvisu.de ist nicht für den Pi2.
Du hängst aber nicht an der USB-Schnittstelle sondern schon vorher.
Das Zauberwort heißt arm. Die Beschreibung auf die Du Dich beziehst 
(speziell der eibd-Part) ist wohl für Intel.
Für arm müsste die sources.list editiert werden, da die TU Wien arm wohl 
nicht "unterstützt".
Das wie erspar ich mir.

Schonmal "Pi2" in die erweiterte Suche eingegeben? Bei Quellen 
smarthome.py auswählen und los.
Dann einfach mal einen Blick ins 2te Suchergenis werfen und dort dann 
den Post #8.
Um genau zu sein:
Oder einfacher: 
http://knx-user-forum.de/forum/supportforen/smarthome-py/42446-pi-2-mit-raspbian-neuinstallation?p=678618#post678618
Einfacher geht es wirklich nicht.

Zu den REG-USB-Schnittstellen generell sei gesagt. Merten und GIRA 
funktionieren ohne Probleme.
Einige andere wie z.B. ABB und Ling&Jancke können zicken (read).
Über die richtigen Einstellungen in der eibd auf dem PI klappt das aber 
dann auch. Aber da hab ich nicht die Zeit und Lust das rauszusuchen.

viel Erfolg!




Am 02.02.2016 um 19:40 schrieb hellobello:

**Comment by smaiLee** [comment]
The image isn't part of smartVISU project, please find support by provider of images in the KNX Use Forum.

**Comment by onnlinetool** [comment]
Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden 

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi
