### ISSUE TITLE
Problem with google calendar

### ISSUE THREAD

**Issue by zobi** [Martin-Gleiss/smartvisu#58]
I cannot print my calendar. 

Apache log : 
[Fri Jul 08 21:03:34 2016] [error] [client 192.168.2.254] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /Dropbox/Domotique/KNX/smartVISUng/lib/calendar/service/google.php on line 43, referer: http://flyboat.dcddtc.com:8888/smartVISUng/index.php
[Fri Jul 08 21:03:34 2016] [error] [client 192.168.2.254] PHP Warning:  simplexml_load_string(): BEGIN:VCALENDAR in /Dropbox/Domotique/KNX/smartVISUng/lib/calendar/service/google.php on line 43, referer: http://flyboat.dcddtc.com:8888/smartVISUng/index.php
[Fri Jul 08 21:03:34 2016] [error] [client 192.168.2.254] PHP Warning:  simplexml_load_string(): ^ in /Dropbox/Domotique/KNX/smartVISUng/lib/calendar/service/google.php on line 43, referer: http://flyboat.dcddtc.com:8888/smartVISUng/index.php
[Fri Jul 08 21:03:34 2016] [error] [client 192.168.2.254] PHP Warning:  Invalid argument supplied for foreach() in /Dropbox/Domotique/KNX/smartVISUng/lib/calendar/service/google.php on line 47, referer: http://flyboat.dcddtc.com:8888/smartVISUng/index.php

I didn't found the solution :/
Thanks a lot

**Comment by smaiLee** [comment]
Maybee this is fixed by Google V3 Calendar API from [commit b829f7a880131ac5eded9f9fcb38c9ae15fc8e5a](https://github.com/Martin-Gleiss/smartvisu/commit/b829f7a880131ac5eded9f9fcb38c9ae15fc8e5a), could someone check please?

**Comment by smaiLee** [comment]
I've found the reason this doesn't work anymore: Google has discontinued the XML calendar service (see https://productforums.google.com/forum/#!topic/calendar/Z9SRXUh93xI).
But reading calendars as iCal by private URL still works, so no need for API v3. I'm working on this so old configuration will work again.
