### ISSUE TITLE
Adjust documentation to 2.8 (new Plots, more information, Releasenotes, etc.)

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#63]
_From @psilo909 on August 21, 2016 4:31_

The new Plots and other things (like the "0h" default instead of 0) need to be adjusted and added in the documentation.

We could also help new users by improving the documentation, as the documentation always was a problem with old SmartVisu.

Moreover, some documentation for developers would be very nice (drivers, new widgets, data handling, etc)

Also take care to log your changes in releasenotes (wiki?)

_Copied from original issue: SmartVisuTNG/smartvisu#16_

**Comment by smaiLee** [comment]
I have created changelog.md in the root, please enter up your changed stuff there.

**Comment by smaiLee** [comment]
The changelog I brought up to date, please check if I missed something. And I copied changelog.md to the [wiki](https://github.com/Martin-Gleiss/smartvisu/wiki/Release-v2.8).

I'm not aware of any missing things in user documentation, are you?

Developer documentation would be nice but is a separate topic not for 2.8.

**Comment by i-am-offline** [comment]
While testing stuff for #64 I found some more small issues in the docu pages. I'll fix them and push this afternoon
