### ISSUE TITLE
Have some kind of page checker

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#64]
_From @i-am-offline on August 22, 2016 4:48_

It would be good to to have some kind of page checker that checks a set of pages for probable issues. 
The main issue which needs checking at the moment is, that the .png icons have been replaced by .svg icons in v 2.8.

The page checker should have three main functions
- Check pages for issues and show them.
- Propose solution (possibly editable).
- Apply solution to file if user wants to.

_Copied from original issue: SmartVisuTNG/smartvisu#20_

**Comment by i-am-offline** [comment]
I have added a pr for my first draft of a template checker. It currently focusses mainly on images, because due to the change from png to svg images I expect this to be the most important checks for now.

**Comment by smaiLee** [comment]
This was added and works.
For requesting additional checks separate issues should be opened.
