### ISSUE TITLE
Drop support for iconseries in basic.shifter

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#65]
_From @i-am-offline on August 22, 2016 4:57_

basic.shifter works perfectly with svg-images. 
Iconseries are a hangover from the .png era. I've made basic.shifter with iconseries work basically while working on #14, but I consider this as outdated.

It should be discussed if iconseries support in basic.shifter can be dropped. However, there are some nice iconseries (e.g. fts_garage*) which should be converted in a dynamic svg-image first.

_Copied from original issue: SmartVisuTNG/smartvisu#21_

**Comment by Martin-Gleiss** [comment]
It can be dropped.

**Comment by wvhn** [comment]
Closed w/ PR #372
