### ISSUE TITLE
Configuration Page: Changes not visible after save

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#66]
_From @smaiLee on August 22, 2016 14:6_

After pressing "save" on configuration page, the old values are displayed again.
But the changes are saved and after refresh they are also shown on configuration page.

_Copied from original issue: SmartVisuTNG/smartvisu#22_

**Comment by smaiLee** [comment]
_From @psilo909 on August 22, 2016 14:20_

den gibts aber schon seit ich die SV kenne ;-) oder ist das nur zum tracken des issues?

**Comment by smaiLee** [comment]
Deshalb hat er ja auch das Label "older than 2.8". Gefixt werden sollte er ja trotzdem irgendwann.

**Comment by smaiLee** [comment]
_From @psilo909 on August 22, 2016 14:23_

gutgutgut ich bin blind :)

**Comment by smaiLee** [comment]
solved by #74

**Comment by bmxp** [comment]
I am not sure we solved it already. If you select a new Style e.g. Cube instad of night and you press save then the results are shown immediately. But try to change the hostname or ip for the driver's destination or also the pages selection you will find that this change is not honored at all. 
It seems as if it is just working for things that have to do with Twig and not with PHP config settings. 

To fix this we might have several approaches. One can be as follows: Disable the ZendOpcaching from apache2 for PHP. You can try it out: 

```
/etc/php5/apache2/conf.d$ sudo nano 05-opcache.ini
```
comment out the line **zend_extension=opcache.so** and save it again. Afterwards restart Apache with **sudo systemctl restart apache2**

If you now use save then the new set data is posted via JQuery AJAX and upon success after a delay (typical 750) the whole pages is reloaded.
A more professional way can be to disable the zend_extension at full.

Another way can be to edit the .htaccess for the directory where we want to prevent caching form and include **php_flag opcache.enable Off**

**Comment by bmxp** [comment]
IMHO it would also be a good thing to show a kind of dialog box to inform the user about the data save process and the reload after it; ideally preventing other inputs in the meantime...

**Comment by smaiLee** [comment]
I finally found the cause and the solution:
The config.php is saved but the new values are not immediately available as the config.php is "read" by including it. As PHP has a caching mechanism for compiled scripts, the immediately after saving uses the old version.
Calling the php function [opcache_invalidate()](http://php.net/opcache-invalidate) for config.php solves this by invalidating the cache.
I will fix this in develop branch.

**Comment by bmxp** [comment]
If you really fix it by implementing the above then you should consider merging it into master since IMHO that's a hotfix which should be applied to all installations in the field. If you don't then people start again to use develop as productive basis ...

**Comment by smaiLee** [comment]
As users rarely change configuration and the workaround to refresh the page some seconds after save is not big deal i wont do this in master.
I would rather have this tested well in develop. And next release should not take 3 years...

**Comment by bmxp** [comment]
Well, I hope not ;-) But I won't expect it this year either ...
