### ISSUE TITLE
Issues with minutes in data-repeat

### ISSUE THREAD

**Issue by tukey42** [Martin-Gleiss/smartvisu#691]
As far as I understood, data-repeat expects a time string to automatically update a widget. 15m is supposed to stand for every 15 minutes (this is e.g. the default in phone.list). Unfortunately the method "duration" defined in base.js uses "m" for months and "i" for minutes. Therefore the phone.list is updated every 15 months (if not explicitely specified otherwise.

**Comment by wvhn** [comment]
The duration format is used for data-repeat, too. Hence '15i' is the right expression to set the repeat interval to 15 minutes. This has been faulty in earlier versions but the issue has been fixed with #500 in v3.1 by setting the default values in the phone widgets to 15i.
