### ISSUE TITLE
Deleting cache leads to "HTTP Error 500" 

### ISSUE THREAD

**Issue by jksd** [Martin-Gleiss/smartvisu#696]
Hi, 
after upgrading from v3.1 to v3.2 cache behaviour seems to be different. When deleting temp/* smartvisu couldn't be loaded any more. Same after disabling cache in config.ini.

After restoring the temp directory, smartvisu v3.2 ist working again.

Best regards, Jörk

**Comment by wvhn** [comment]
You should not delete the entire temp folder. Just delete the subfolders of it and leave all other files unchanged. 

Please make sure smartVISU and its subfolders are owned by the right user and group (on a Raspberry Pi with smarthomeNG the group is "www-data" and the user "smarthome". Set the file / folder rights to 775 for all folders. Then please run the template checker to test the requirements and also check whether temp folder is writeable for the current user.

If you need further support, come to the forum: https://knx-user-forum.de/forum/supportforen/smartvisu

Best regards
Wolfram

**Comment by jksd** [comment]
Hi Wolfram,
I haven't deleted temp directory. I deleted only subdirs and files contained by temp. 
With another test, I kept subdirs "pagecache" an "twigcache" and deleted content of pagecashe an twigcache -> same result. After git checkout temp directory from my git repo (temp content was checked in before), smartvisu was starting normally.

With v3.1, I had no problem doing this deletion (just double checked it a minute ago).
What happens, if you remove subdirs and files of temp ?

Best regards,
Jörk

**Comment by wvhn** [comment]
I have deleted the cache folders more than once without problems and so did other users. So I'd like to find out what is causing this behaviour in your installation.

Please come to the forum. There you can send me a privat message with a link to a cloud storage containing your entire SV folder. I'll test it in my environment.

BR Wolfram

**Comment by jksd** [comment]
Hi Wolfram,
I've set up my v3.2 from scratch again. And this time, everything works fine. Deleting content of temp directory behaves like previous versions (ok). Thank you for your support and your patience. Sorry for the inconvenience.
Best regards, Jörk
