### ISSUE TITLE
Online-Status

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Martin-Gleiss/smartvisu#7]
```
Eine Anzeige (z.B. oben rechts beim sv-icon) welche den aktuellen Status 
anzeigt. jeweils nach Farben grün=ok, gelb=info, rot=offline)
Gleichzeig (z.B. darunter einen Zeitstempel wie lange der Zusatnd so ist. 
Beispiel: grünes Icon und darunter der Text 
Online seit xx Tagen: xx Stunden xx Minuten 


```

Original issue reported on code.google.com by `Montgomery.Burns72@gmail.com` on 13 Apr 2013 at 10:53

Attachments:
- [Unbenannt.jpg](https://storage.googleapis.com/google-code-attachments/smartvisu/issue-7/comment-0/Unbenannt.jpg)

**Comment by smaiLee** [comment]
Ich sehe da eigentlich kein Bedürfnis. Wenn die Verbindung zum Backend abbricht, wird das mit einem roten Error in der Ecke gemeldet.
Falls jemand darauf besteht, bitte wieder öffnen.
