### ISSUE TITLE
Leading "0" in numeric values get cutten

### ISSUE THREAD

**Issue by psilo909** [Martin-Gleiss/smartvisu#73]
At the moment, the basic.value is cutting of leading "0"s e.g. in phone numbers. I think the number is treated as numeric value and not as STR.

![hfgh](https://cloud.githubusercontent.com/assets/15831643/18032602/e2c0e842-6d09-11e6-96b5-7673738c388c.PNG)

**Comment by smaiLee** [comment]
Your right, any numeric value is treated as number.
A solution could be to introduce a unit named 'text' which would prevent any formatting.

**Comment by psilo909** [comment]
@smaiLee die Kategorisierung als Feature gefällt mir nicht, mE ist das ein Bug ... Ok jetzt habe ich wieder gestichelt.. Sorry :) Aber die Diskussion über Bug oder nicht Bug führe ich am normalen Arbeitstag mind 10x

**Comment by smaiLee** [comment]
Obs dir gefällt oder nicht, basic.value ist dem Namen nach wohl primär für Werte und nicht für Text gedacht.
Als Workaround kannst du basic.text verwenden und zwei mal denselben Text verwenden oder ein Item verwenden, das den Wert nie ändert.
Oder du sorgst bei basic.value durch ein zusätzliches Zeichen im Parameter dafür, dass [jQuery.isNumeric](https://api.jquery.com/jQuery.isNumeric/) zu false wird.

**Comment by psilo909** [comment]
Wie ich das für _mich_ löse ist mir schon klar, ganz dumm bin ich ja auch nicht.

Für mich sagt das Wort "VALUE" aber nicht aus, dass es hier um numerische Werte geht. Value ist ein Wert, auch ein STRING kann einen Wert haben. Fehlt dem Wert etwas, ist es ein Bug.

Würden wir hier über ein Basic.Float, ein (nicht existentes) Basic.Int oder ein (ebenfalls nicht existentes) Basic.Number reden ok, aber ein Value ist aus meiner Sicht vom Wort her sehr neutral geprägt und drückt nicht wirklich einen Zahlenbezug aus.

Sinnigerweise schreibe ich mir halt ein Basic.StrValue und verwende das für mich, schade ist, dass mit dem default Value-Widget eines unserer in SHNG mitgelieferten Widgets mit der SV nur teilweise korrekt funktionieren wird. Meinen Workaround behalte ich für mich, was mit einem PR passieren würde kann ich jetzt schon orakeln.

**Comment by psilo909** [comment]
Ich teste jetzt folgenden Workaround:

set: function (item, value) {

		// case: a series
		if (widget.buffer[item] instanceof Array) {
			// arrays passed by reference so no need to add it to the buffer, the caller (driver, highchart, ...) will do it.   
			//var series = widget.buffer[item];
			//series.push(value);
		}
		else if (value !== undefined) {
                    if ((String(value).charAt(0) == 0) && $.isNumeric(String(value).charAt(1))) {
                        widget.buffer[item] = ( value);
                    } else {
			widget.buffer[item] = ( $.isNumeric(value) ? value * 1.0 : value);
                    }
		}

		// DEBUG: console.log("[widget] '" + item, widget.buffer[item]);
	},

**Comment by psilo909** [comment]
Vermutlich sollte noch ne Längenprüfung rein, aber jetzt geh ich erstmal 20km laufen..

**Comment by psilo909** [comment]
Kurztest: führende 0 geht, und normale "numerics" mit nur 1 Stelle offenbar auch ohne Fehler.. Tiefere Analyse später. Gerne kannst Du es aber auch komplett abschlagen und ich merge halt in Zukunft. Jeden der beim AVM Plugin Probleme hat weil basic.value die 0 verschluckt werde ich trotzdem auf die Impl. in der SV verweisen. Vielleicht aber etwas diplomatischer...

![gdfg](https://cloud.githubusercontent.com/assets/15831643/18229276/29776bb2-7273-11e6-9e80-01395612b7d9.PNG)

**Comment by smaiLee** [comment]
Wenn du die Lösung eh schon programmiert hast, warum erstellst du dann einen Issue und machst keinen PR? Die mögliche mitarbeit ist ja einer der Vorteile von Open Source.

Es gibt anscheinend 2 Stellen im Code, wo die Zahlen umgewanelt werden.
Ich habe das Problem in [widget.js auf Zeile 581](https://github.com/Martin-Gleiss/smartvisu/blob/master/widgets/widget.js#L581) gesehen, also beim basic.value Widget, wie du auch im Titel schreibst.
Dein Ausschnitt scheint aus base.js zu stammen. Dort wirkt sich das aber auf alle Widgets aus, was tatsächlich ein Bug ist.

Mich stört noch etwas, dass in deinem Vorschlag Zahlen mit führenden Nullen auch in bestehenden Anwendungen plötzlich als String behandelt würden und die Korrektur damit nicht ganz Rückwärtskompatibel ist. Allerdings habe ich im Moment auch keine Lösung dafür.

**Comment by psilo909** [comment]
Für die eine Zeile Code werde ich das jetzt nicht machen, Du darfst gerne entscheiden, ob Du das verwerten möchtest oder nicht. Der Issue besteht ansich jetzt ja.

Danke für die Umklassifizierung.
