### ISSUE TITLE
SmartHomeNG new - Add path for websocket

### ISSUE THREAD

**Issue by CornholioLU** [Martin-Gleiss/smartvisu#734]
Hi,
with the new driver for smarthomeng it is not possible to add a path for the websocket (for example wss://mydomain.com/mysmarthomewebsocket). 
The quick fix was to update io_smarthomeng.js and append it, changing  line 164
`io.socket = new WebSocket(protocol + io.address + ':' + io.port);`
to this
`io.socket = new WebSocket(protocol + io.address + ':' + io.port + '/websocket');`

Would you consider adding this as an option in the driver configuration?

Thanks

**Comment by wvhn** [comment]
Hi,
thanks for the contribution. Have you tried to provide the path with the port? It should be sufficient to enter e.g. `2424/websocket` into the port config field and `2425/websocket` into TLS-port.

**Comment by CornholioLU** [comment]
Hi, 
adding the path to the port field works.
Thanks
