### ISSUE TITLE
Auto Reconnect not working as expected

### ISSUE THREAD

**Issue by msinn** [Martin-Gleiss/smartvisu#75]
When I turn on **Auto Reconnect** in the I/O-Connection, my visu starts displaying wring information:

Items are displaying the right information, as long as i use the items in the pages itself. The display of status icons which is handled in widgets in my visu, displays the wrong information.

Example:

I have an item `wohnung.buero.tv.status`which has the value of 6. The value is displayed correctly by the following statement: {{ basic.value('az_tv2', 'wohnung.buero.tv.status') }}

My macro for displaying the icon:
```
/**
 * Display status icons on page
 * 
 * @param       id: 	unique id for this widget
 * @param       gad:	the gad/item as source for the status information:
 *
 * @param       icon: basename of the icon to display
 */
{% macro status_picon(id, gad, icon) %}
    {% import "basic.html" as basic %}
    {{ basic.symbol(id~'status0', gad, '', icon0~icon~'.svg', '0', '', '#25ea4e') }}
    {{ basic.symbol(id~'status1', gad, '', icon0~icon~'.svg', '1') }}
    {{ basic.symbol(id~'status2', gad, '', icon0~icon~'.svg', '2') }}
    {{ basic.symbol(id~'status3', gad, '', icon0~icon~'.svg', '3') }}
    {{ basic.symbol(id~'status4', gad, '', icon0~icon~'.svg', '4', '', '#4176a9') }}
    {{ basic.symbol(id~'status5', gad, '', icon0~icon~'.svg', '5', '', '#4176a9') }}
    {{ basic.symbol(id~'status6', gad, '', icon0~icon~'.svg', '6', '', 'icon1') }}
    {{ basic.symbol(id~'status7', gad, '', icon0~icon~'.svg', '7', '', '#a00000') }}
{% endmacro %}
```
Should display the icon in color 'icon1' (which is orange for the night design) but it is shown in white. So either the color is 'lost' or the widget thinks the status is '1', '2' or '3'.

When I turn of **Auto Reconnect**, all is back to normal and functioning just fine.

**Comment by smaiLee** [comment]
Fixed by recreating outdated base.min.js (sorry for this)
