### ISSUE TITLE
Update Twig to 2.x or even better 3.x

### ISSUE THREAD

**Issue by bmxp** [Martin-Gleiss/smartvisu#752]
We should consider to update Twig since the current version 1.44.6 which was lastly update in November 2021 will not receive any fixes neither functional nmor security wise.

There was already an [issue](https://github.com/Martin-Gleiss/smartvisu/issues/95) earlier.

One breaking change is about [macros](https://twig.symfony.com/doc/1.x/deprecated.html) where it states:

>As of Twig 2.0, macros imported in a file are not available in child templates anymore (via an include call for instance). You need to import macros explicitly in each file where you are using them.

**Comment by wvhn** [comment]
Twig 2.x/3.x breaks the entire loading concept of widget macros in smartVISU. And so it will break all users pages if we update. Also, the import from ./dropins and its subfolders will not work any more, thus breaking the concept of plugin-specific widgets from smarthomeNG.

Up to now there is no proven concept for loading Twig macros globally in Twig 2/3. I have tried to address this to the development team but the answers were not really supportive.

So until there are no real issues coming up with the old Twig version I am not going to touch this.

**Comment by bmxp** [comment]
That's a good point. So I'll close this :-)
