### ISSUE TITLE
codepad isnt't working anymore

### ISSUE THREAD

**Issue by thorschtn** [Martin-Gleiss/smartvisu#77]
In the old unofficial 2.8 the codepad worked well. In smartvisuNG 2.9 and same in the merged master Martin-Gleiss/smartvisu while opening the codepad-popup the switch is executed already without requiring the PIN.

**Comment by Martin-Gleiss** [comment]
event.stopPropagation(); seems not working in device.html

**Comment by smaiLee** [comment]
Bug was introduced by my performance patch.
Click events are now bound directly to the widget. So the event is handled by the protected widget before codepad can handle it.
I'll try to fix it.
