### ISSUE TITLE
Widget "plot.temprose" not working on mobile device

### ISSUE THREAD

**Issue by aschwith** [Martin-Gleiss/smartvisu#78]
Not working on mobile device (tested with Android 5.0.1)

Working fine one regular browser (Firefox 48.0.2)

Can anyone confirm this issue?

**Comment by smaiLee** [comment]
At least the temprose on the docu page does work in chrome and samsung browser on android 4.4.2 on tablet and mobile phone.

**Comment by aschwith** [comment]
Correct. One temperature value was not initialized. My fault. Issue can be closed.
