### ISSUE TITLE
Extend plot.period to show different times of same item for SmartHomeNG

### ISSUE THREAD

**Issue by bmxp** [Martin-Gleiss/smartvisu#787]
To compare different times from data series from the same item the websocket protocol would need an extension. See also [#502](https://github.com/smarthomeNG/smarthome/issues/502) at SmartHomeNG Core

**Comment by wvhn** [comment]
The same item can be subscibed at shNG mutliple times with different durations. I am working on the plot widget to allow this. A websocket protocol extension is not needed.
