### ISSUE TITLE
Not all dynamic icons work as they should

### ISSUE THREAD

**Issue by msinn** [Martin-Gleiss/smartvisu#79]
Some dynamic icons should show motion (e.g. icon.windmill, icon.ventilation). 

In v2.7 that worked at least sometimes. In the actual version there is no animation. The icons are just static.

icon.light should show light rays. On the doc page icon.light is static.

**Comment by smaiLee** [comment]
Icons windmill and ventillation do work if I reload the icon page. If I reload on another page and then navigate to icon page they are not animated.
The light doesn't react at all.

**Comment by smaiLee** [comment]
Remarkable: Same bahaviour can be senn at docu page of basic.shifter (animation and light bulb).
So it's likely a general bug and not just a wrong definition on one docu page.

**Comment by msinn** [comment]
I have an widget of my own where I have a light bulb that works. This evening I'll check what the differences are (compared to icon.light.

**Comment by msinn** [comment]
I checked the icon.light icon. It is exactly like the one I use in a different widget.

I remember, that I extracted the dynamic Icons I use for 2 reasons: 

First, not all icons where working when I used the icon widget from SV.
Second, them I install them with the visu_smartvisu plugin, the include statements are generated by visu_smartvisu.

Probably the fault is somewhere in the icon.html or widget.js code.

**Comment by smaiLee** [comment]
I've fixed the light bulb, this one was a bug in widget.js

And I've analyzed the animation problems:
In chrome the behaviour is as I wrote before.
In Firefox the animations do work well.
In IE they don't work at all.

As you can see in [this feature map](http://caniuse.com/#feat=svg-smil) IE and Edge don't support SMIL animations. And in Chrome they are deprecated!
So I think we have to use another technology in future, at the moment I wont fix it.

**Comment by smaiLee** [comment]
As the not properly working *windmill* and *ventilation* are new in 2.8, should they better be removed, what do you think?
Otherwise we release something, that only runs well in firefox.

**Comment by smaiLee** [comment]
Just fixed the animation in Chrome, but SMIL still doesn't work in IE and is deprecated in Chrome, so another solution is needed in  the medium term.

**Comment by wvhn** [comment]
no complaints since v2.9 ->issue closed
