### ISSUE TITLE
Neues Design "FlatDarkBlue" hinzufügen (improve)

### ISSUE THREAD

**Issue by uwe5** [Martin-Gleiss/smartvisu#794]
Anbei ein neues Design, wäre schön wenn es ins nächste Release kommt.
Gruß Uwe
![ksnip_20221117-174921](https://user-images.githubusercontent.com/25882945/202508900-13b26f04-20fb-417d-885a-07012e9b1fe8.png)

[FlatDarkBlue.tar.gz](https://github.com/Martin-Gleiss/smartvisu/files/10033765/FlatDarkBlue.tar.gz)

**Comment by wvhn** [comment]
sieht cool aus. Nehme ich ins develop.
Danke!

Gruß
Wolfram
