### ISSUE TITLE
no plot update on item change (iobroker)

### ISSUE THREAD

**Issue by uwe5** [Martin-Gleiss/smartvisu#805]
Wenn bei einem Plot Widget ein Item neue Daten bekommt so wird der aktuell angezeigte Plot nicht upgedatet.
Getestet mit ioboker & plot.period.

Soweit ich herausfinden konnte wird kein io.stateChanged(id, state) (in io_iobroker.js) bei Item-Wert-Änderung aufgerufen.

**Comment by uwe5** [comment]
Hier ein Beispiel vor BrowserRefeshButton drücken:
![ksnip_20221214-194308](https://user-images.githubusercontent.com/25882945/207685013-7196d08e-0785-4f2d-b56c-7dd9cb2fbc4d.png)

Und hier nach BrowserRefeshButton drücken:
![ksnip_20221214-194314](https://user-images.githubusercontent.com/25882945/207685149-d68296bd-e0c5-45d2-9491-9a011f6db7e1.png)

**Comment by wvhn** [comment]
While an item subsribed is e.g. 'test.temperature', the plot data id subscribed out of the history of that item is e.g. 'test.temperature.avg.2d.now.100'. So the plot will not update with stateChanged of the normal item but with a new array consisting of timestamp and value delivered by the history database (in the given sampling interval and aggregation mode) in this form: ` [[1670971939225, 32.0], [1670971971635, 32.0]]`. 
Up to now,  this is not implemented in the driver and (most likely) neither in ioBroker.
Maybe @Apollon77 can support to implement this on ioBroker side. I can then adapt the driver.

**Comment by uwe5** [comment]
Ok, ich verstehe, subscribed fehlt bei den Plots.
Habe folgende Änderung in io_iobroker.js gemacht: Plots werden jetzt mit subscribed, und das ganze auch in stateChanged bei einem Plot die Plotdaten neu holen lassen.
Das Ergebnis
![PlotsSmartVisu](https://user-images.githubusercontent.com/25882945/207868845-1d1495b4-8c69-418e-8c9c-a36fc60956b4.gif)
:
[io_iobroker.tar.gz](https://github.com/Martin-Gleiss/smartvisu/files/10237266/io_iobroker.tar.gz)

**Comment by wvhn** [comment]
Thanks!
Merged into develop branch with PR #806

**Comment by uwe5** [comment]
On a mobile phone this is still a bit slow when the page is called up for the 1st time. I optimized that.
Start subscribing with a delay in the plots so the "normal" widgets are populated with data first. This speeds up page loading when there is a lot of data in the plots.
[io_iobroker.tar.gz](https://github.com/Martin-Gleiss/smartvisu/files/10238933/io_iobroker.tar.gz)
