### ISSUE TITLE
 UZSU unter ioBroker

### ISSUE THREAD

**Issue by uwe5** [Martin-Gleiss/smartvisu#810]
Hallo Wolfgang,
Ich habe da noch was gebacken: UZSU unter ioBroker verwenden, ganz einfach..
![UZSU Tannenbaum](https://user-images.githubusercontent.com/25882945/208253856-d9758e94-f68c-42e4-b9eb-23c32857055f.gif)

Dazu habe ich ein UZSU-Scheduler unter ioBorker für das smartVisu UZSU Widget geschrieben. Dieser läuft unter ioBroker und führt dann den eingestellten Timer aus.

Wie könnte man das Dokumentieren?
Möchtest Du dies im GIT Projekt smartvisu hinterlegen?
etwa so: unter smartvisu/driver/ die zwei Dateien (siehe tar.gz) hinterlegen?

Gruß Uwe
[iobroker_uzsu.tar.gz](https://github.com/Martin-Gleiss/smartvisu/files/10252200/iobroker_uzsu.tar.gz)

**Comment by wvhn** [comment]
Klasse! Ich kann das in einem Unterordner „ioBroker“ bei den Treibern ablegen und eine Readme dazu schreiben.  

Eigentlich ist die „universelle Zeitschaltuhr“ (UZSU) ja eine Erweiterung von ioBroker, die vlt. auch für andere User interessant ist. Das Widget macht ja nichts anderes, als die Schaltzeiten abzufragen und in ein Dict für die Scheduler des Backends zu schreiben. Das Dict ist zwischen smarthomeNG und fhem / fronthem weitgehend standardisiert. Es wäre super, wenn sich ioBroker da anschließen würde. 
@Apollon77, ist das für Dich interessant?

**Comment by Apollon77** [comment]
Naja in ioBroker wäre das entweder ein Adapter den man dann installieren würde oder als Custom Javascript was dann über states (oder inzwischen messages) gesteuert werden könnte.
Müsste man mal überlegen.

Am Ende wäre denke sinnvoll mal Details zur "Schnittstelle"/Daten und so als AdapterRequest anzlegen, dann kann ich mal schauen ob jemand Zeit hat. Wenn jemand schon ein JS dafür hat ist das noch einfacher zu übernehmen.

**Comment by uwe5** [comment]
> Naja in ioBroker wäre das entweder ein Adapter den man dann installieren würde oder als Custom Javascript was dann über states (oder inzwischen messages) gesteuert werden könnte. Müsste man mal überlegen.
> 
> Am Ende wäre denke sinnvoll mal Details zur "Schnittstelle"/Daten und so als AdapterRequest anzlegen, dann kann ich mal schauen ob jemand Zeit hat. Wenn jemand schon ein JS dafür hat ist das noch einfacher zu übernehmen.

Ja, genau dass ist hier ja realisiert worden (Custom Javascript). 

Gruß Uwe

**Comment by Apollon77** [comment]
Dann alle infos und das Skript ab in einen AdapterRequest :-) Und gern bis dahin als "Anleitung" ins Forum.

Ich hoffe ich finde die Tage zeit den smartvisu Adapter mal zu aktualisieren

**Comment by wvhn** [comment]
Die Dateien liegen jetzt in ./driver/iobroker_uzsu/. #811 
(Der Ordner "iobroker" wäre für Treiber-Erweiterungen reserviert und .js-Dateien würden von dort automatisch importiert).
