### ISSUE TITLE
typeof item-value was changed when writing back to ioBroker

### ISSUE THREAD

**Issue by uwe5** [Martin-Gleiss/smartvisu#814]
Hallo Wolfram,

Kurz:
Aus true oder false wurde nummerisch 1 oder 0 auf ioBroker-Seite (im ioBroker Object) gespeichert obwohl vorher true bzw. false dort stand. 

Lang:
Ich hatte Probleme wenn boolean-Werte aus ioBroker gelesen werden und durch z.B. basic.checkbox wieder Richtung ioBroker geschrieben werden. Der write-request in io_broker.js wandelte den Boolean-Wert in eine Zahl um, ioBroker benötigt aber an dieser Stelle wieder den originalen Datentypen, wie sie mit read-request gelesen wurde. Bei anderen Datentypen (Array mit basic.color und hsv) war auch noch ein ähnliches Problem. Das alles habe ich behoben indem ich den originalen Datentyp beim lesen aus ioBroker merke und beim zurückschreiben wieder in den originalen Datentypen konvertiere.

Ich habe das ganze mal mit diesen Widgets getestet:
`{{ basic.checkbox('', '0_userdata.0.boolean_value', 'boolean', '1', '0') }}
{{ basic.checkbox('', '0_userdata.0.boolean_value', 'boolean', 1, 0) }}
{{ basic.checkbox('', '0_userdata.0.boolean_value', 'boolean', true, false) }}
{{ basic.stateswitch('', '0_userdata.0.boolean_value', 'icon', ['1','0'], ['jquery_plus.svg', 'jquery_minus.svg']) }}
{{ basic.stateswitch('', '0_userdata.0.boolean_value', 'icon', [1,0], ['jquery_plus.svg', 'jquery_minus.svg']) }}
{{ basic.stateswitch('', '0_userdata.0.boolean_value', 'icon', [true,false], ['jquery_plus.svg', 'jquery_minus.svg']) }}`
Es macht kein Unterschied mehr ob man '1','0' oder 1,0 oder true,false angibt. Es wird immer richtig wieder ein boolean zurückgeschrieben.

`{{ basic.color('', '0_userdata.0.HSBColor', '', '', '', '', '', '', 'rect', 'hsv') }}`
Hier war das Problem das "h,s,v" nach "[h,s,v]" falsch mit Klammern zurückgeschrieben wurde.

Auch getestet:
`{{ basic.flip('flip', '0_userdata.0.boolean_value') }}
{{ basic.select('', '0_userdata.0.basicselectitem', '', '', '', '', '', '', '0_userdata.0.basicselectitemvals', '0_userdata.0.basicselectitemtxts') }}`

Anbei die gefixte io_broker.js.

Gruß Uwe
[io_iobroker.tar.gz](https://github.com/Martin-Gleiss/smartvisu/files/10261100/io_iobroker.tar.gz)

**Comment by wvhn** [comment]
Super.  Bist Du durch mit Deinen Änderungen? Ich stehe nämlich ganz kurz vor dem nächsten Release.

**Comment by uwe5** [comment]
Ich glaube schon, zumindest für alle Widgets die ich hier bei meiner Haussteuerung verwende, habe ich jetzt eine funktionierende Kopplung der Datenelement mit/von ioBroker. 

Ein Problemchen habe ich noch:
wenn ich in der Menüseite ein PopUp als weiteren Menüpunkt definiere geht der PopUp nur auf wenn ich in der Hauptseite bin. 
![PopUp](https://user-images.githubusercontent.com/25882945/208490200-bc967d9d-36e8-4b04-aa49-174e2e05ae18.gif)


Dafür habe in rooms_menu.html folgende eingefügt:
![ksnip_20221219-190719](https://user-images.githubusercontent.com/25882945/208491443-e2b4ef78-677c-4416-8fc9-b3a13f31a0f5.png)

**Comment by wvhn** [comment]
es wäre gut, wenn Du für solche Fragen ins [Forum](https://knx-user-forum.de/forum/supportforen/smartvisu) kommen würdest. Da kann das einfacher beantwortet und für alle besser dokumentiert werden.

jQuery mobile wird im Multipage-Modus betrieben. Deshalb müssen alle IDs eindeutig sein. Das Popup geht schon auf, aber eben nur auf der Seite, auf der es zuerst definiert wurde. 
Wenn Du statt `#popup3` `#{{ page }}-popup3` verwendest und analog `id="{{ page }}-popup3`, dann legt twig das Popup auf jeder Seite mit einer individuellen ID an.

Gruß
Wolfram

**Comment by wvhn** [comment]
erledigt mit #815
