### ISSUE TITLE
Harmonize and extend icon handling and stylabiliy in widgets

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#82]
As discussed in #80 

At the moment there are some widgets with seperate color parameter, others need CSS. And some handle SVG and PNG seperate, others do just print out the given file as .
And only SVG with class icon1 are made inline and thereby stylable by CSS. But what if a theme wants to have a default color other than white?

I would suggest the following:
Every theme defines 3 or 4 colors and with any icon you can use one of them. If you don't pass a color, color no 1 is used as primary and no 2 is used as alternative (e.g. on switches).

And I would let the user specify the icons without .svg suffix. If we decide anytime in the future to use something different (as font, background image, css masking or what ever), the users do not have to change anything.

**Comment by msinn** [comment]
I think all icons should be colorizable thru css (icon0, ...) and individual color.

At the moment I am harmonizing all widgets I stumble upon to accept icon0, icon1 and #color. 

Depending on the use, default colors are icon0 or icon1 (e.g. for basic.switch).

When we add further colors (which I think we should do), they should have a described use, like icon0 (off) and icon1 (on) have.

**Comment by smaiLee** [comment]
The defined use I had in mind as well but then decided to not mention it, because I'm of two minds about this. I'm not sure if everyone needs same use cases.

So in my house I use 4 different classes:
- off
- on
- ok
- 'highlight' (or 'warning' or something similar).  
This one actually has the same color as 'on', but i would prefer a separate class to differ them.  

In addition i could think of a fifth one:
- error

But are this the required states for other environments?
If yes, i would name them by their use as listet above instead of just use icon0/1/2/3/4.

**Comment by msinn** [comment]
We could also name additional color iconrd, iconbl and have a red and a blue that harmonizes with the design. So When someone needs blue (like me) he gets a blue that fits the design.

**Comment by smaiLee** [comment]
Di you mean this as alternative or supplementary approach?
In other words: Would you still have classes as on/off/warning/error or just have de color names?

Either way I prefere to not call the classes 'icon' but something like 'theme' or 'color', because they can be used for text too.

Another approach would be to use the swatches of [jQuery mobile ThemeRoller](http://themeroller.jquerymobile.com/). The advantage would be that themes could be created by ThemeRoller.

**Comment by wvhn** [comment]
closed with #745 .
All widgets can be styled using 6 icon classes (icon0 through icon5) or color names / hex color codes.
svg get loaded via twig {{source}} function directly to the html DOM. This boosts performance as these icons don't need to be converted / re-written by fx.init function.
