### ISSUE TITLE
icons in dropin folder not found

### ISSUE THREAD

**Issue by kaiminator** [Martin-Gleiss/smartvisu#820]
Hi,

i placed custom icons in the smartvisu/dropins/icons/ws  folder:

`-rw-r--r-- 1 www-data www-data 19825  7. Dez 10:14 sani_heating_boost.svg
`

This worked so far for 3.2.2. In 3.3 there is an 404 error in the js console

jquery-2.2.4.min.js:4          GET https://smartvisu.xxxxx.de/smartvisu/icons/ws/sani_heating_boost.svg 404

Also, after several minutes, the comes an error in the js console

`Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received`

**Comment by wvhn** [comment]
Hello Kai,
Please provide the widget call with the parameters you are using.

Regards
Wolfram

**Comment by kaiminator** [comment]
> Hello Kai, Please provide the widget call with the parameters you are using.
> 
> Regards Wolfram

`{{ basic.stateswitch('', 'Heizung_Arbeitszimmer_Modus', 'icon', ['boost','manual' ['sani_heating_boost.svg','sani_heating_boost.svg'],'',['icon1','icon0'],'blink') }}
`

fyi: i see the icon in my visu, but maybe it is cached.

**Comment by wvhn** [comment]
Hi,
please check whether the code above contains a copy/paste mistake. After the first line, a closing bracket and a comma are missing: `],` .
When I use the corrected code, the icon is displayed correctly and there is no console message. Since the icon is loaded directly by the twig template engine on server side there can't be any javascript error. 
So I guess it's either faulty widget parameters or the cache (smartVISU and browser) is not cleared.

**Comment by wvhn** [comment]
@kaiminator 
can this be closed or are there still error messages while loading icons from ./dropins/icons/ws?

**Comment by kaiminator** [comment]
Hey,

this is still an issue - the code above has errors regarding c/p, the original code is without mistakes. For example

{{ basic.stateswitch('', 'Heizung_Badezimmer_Modus', 'icon', ['boost','manual'], ['sani_heating_boost.svg','sani_heating_boost.svg'],'',['icon1','icon0'],'blink') }}

**Comment by wvhn** [comment]
Can you please attach the icon „sani_heating_boost“ here? I guess it has a `<defs>` section. Most of these are empty or useless but trigger a JavaScript function in smartVISU which stores the defs in the DOM. This function does not search in ./dropins/icons/ws yet. That‘s a fault. 
 
As a workaround you can delete the defs section in the svg.

**Comment by kaiminator** [comment]
There is a defs section. After deleting it, there is no 404 error

Here is the Code for the svg -> [https://pastebin.com/c7pa0cE6](url)

**Comment by wvhn** [comment]
Wow. This svg carries a lot of garbage. 
In such a case it is better to use it with it's full path: "dropins/icons/ws/sani_heating_boost.svg". This forces the legacy loading method to be used which is slower but more versatile in cleaning.

**Comment by wvhn** [comment]
solved with #825
