### ISSUE TITLE
Icons in basic.multistate and basic.dual can't be colored

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#83]
Widgets basic.multistate and basic.dual does not have a color param.
Perhaps there are other widgets affected I didn't see.

**Comment by msinn** [comment]
I' fix them when coloring the dynamic icons.

**Comment by smaiLee** [comment]
This issue is duplicate of or at least overlaps #49

**Comment by msinn** [comment]
Ok, thats identical. We could close issue #49 with a reference to this issue

**Comment by msinn** [comment]
basic.dual has coloring implemented. Only basic.multistate remain.
