### ISSUE TITLE
How to use JSON interface

### ISSUE THREAD

**Issue by wi6436** [Martin-Gleiss/smartvisu#835]
I have been trying to find an example on how the json interface can be used, but I haven't find anything so far. Can it be accessed by an URL? I would be very grateful for seeing a simple example which uses this driver.

**Comment by wvhn** [comment]
Unfortunately, there is no example for this driver and no documentation. A bit of information is available in the forum: 
https://knx-user-forum.de/forum/supportforen/smartvisu/1022407-kommunikation-via-json-dokumentation where I have raised your request for support. 

The driver needs a TCP connection to a server which provides data from the backend. IP address and port must be configured in the config page. 

New php versions throw a warning on line 32 in io_json.php. This must be changed to 
```
$this->val = (isset($request['val'] ) ? $request['val'] : '');
```
I am going to push this to the develop branch with some error handling improvements, asap.

Please come to the forum for further discussion. 

Regards
Wolfram

**Comment by wvhn** [comment]
Changes mentioned have been pushed. There was an additional bug in the io.write()-method.
Further discussion will be going on in the forum.

**Comment by wi6436** [comment]
Dear @wvhn, 

I would like thank you a lot for all the details about the json interface, which you posted here on github and on the KNX forum. Unfortunately I haven't found enough time yet to test it, but it's on my to do list and will certainly start using it soon.

Thank you again and best regards,

**Comment by wvhn** [comment]
Very nice of you. Thanks!
