### ISSUE TITLE
Weather on the main page get updated late

### ISSUE THREAD

**Issue by msinn** [Martin-Gleiss/smartvisu#84]
On the main page ist shows (even after a reload) 13°C, light fog.

The items of my wunderground plugin in shNG shows the right weather: 18°C, sunny.

**Comment by msinn** [comment]
This evening at 21:25 I checkt back at the visu. The picture has changed to night (moon picture) but shows 24,0°C, humidity 41%, wind S 20km/h.

My wunderground plugin shows 20°C, 60% humidity wind NW 17km/h

The wunderground plugin in shNG and the weather configuration in SV use the same location and the same api key.

**Comment by Martin-Gleiss** [comment]
Not a bug, weather is been cached for an our.

**Comment by msinn** [comment]
Ok, but I think 1 hour is too long when the temperature changes 4 to 6 degrees in that timeframe. 

Maybe the caching period should be shortend or it should be configurable.

**Comment by smaiLee** [comment]
IMHO an hour is too long.

For example in my case: I go to work by bike, so I have to decide what to wear in the morning. In an hour at the morning the tempretare can rise some degrees. On bike it's a big difference if its 13 or 18 degrees.

At the moment I don't use the visu, but if i'll ever have a display at the wall i would.

**Comment by Martin-Gleiss** [comment]
You may change line 31 in wunderground.com.php to
`if ($cache->hit(**MINUTES**))`

**Comment by smaiLee** [comment]
What was the itention for this duration? Prevention of generating too much hits on the API key, or is there another reason?

**Comment by Martin-Gleiss** [comment]
Yes and it is faster if you load a page twice

**Comment by Martin-Gleiss** [comment]
And the frequency of new values of the most weather service are up to twenty minutes, by the weather service itself.
