### ISSUE TITLE
Connection error handling in Domotica driver

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#89]
As reported by @wuast94 in [this Gitter message](https://gitter.im/sVISU/Lobby?at=57caf8f0d52261ec344e62f1).

Domotica driver blocks UI instead of showing an error message on connection error.
If the backend doesn't run the following JavaScript exception is thrown and no navigation is possible in SmartVisu.

> WebSocket connection to 'ws://raspberrypi:2121/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by wvhn** [comment]
closed due to end of life of domotiga.
