### ISSUE TITLE
Configuration Improvements for Google Calendar API v3

### ISSUE THREAD

**Issue by thorschtn** [Martin-Gleiss/smartvisu#90]
The configuration of CLIENT_ID, CLIENT_SECRET, REFRESH_TOKEN in smartvisu/lib/calendar/service/googleV3.php should be moved to the central config file, otherwise it becomes overwritten with each update.

**Comment by smaiLee** [comment]
You're absolutely right - I wasn't aware of this when I merged this PR.
Actually we should implement the hole authentication process on config page. But unfortunately this is not done in a minute.

**Comment by smaiLee** [comment]
I did study the current API and possibilities. The following workflow seems feasible to me:
1. On smartVISU configuration is a link which opens a new window.
1. This window shows the instructions how to create Google developer project and webserver credentials.
(including the environment dependent URI which has to be entered as allowed redirectURI)
1. Below there is a form to enter client ID and client secret.
1. This form submits to Google accounts to trigger user's consent and get code (replaces step1.php)
1. Afterwards this code is used to automatically get refresh token (replaces step2.php)
1. The client ID, client secret and refresh token are saved in SV configuration, the popup window closes.
1. Later on Google calendar service driver can use the saved data to get the access token.
This token may be cached, but I'm not sure where I would do this. I see three possibilities:
    1. Class cache in temp folder (not quite appropriate to store secrets)
    2. Configuration file (not quite appropriate to store temp data)
    3. Cookie on client (a new access token has to be obtained for each client)

**Comment by smaiLee** [comment]
It's done, thank you @lolouk44 for translating and refreshing the instructions.

If you like you would be very welcome to translate it to french later on. :smile:
But you may wait for test feedback first as there could be some changes.
