### ISSUE TITLE
make.php doesn't work as expected

### ISSUE THREAD

**Issue by msinn** [Martin-Gleiss/smartvisu#94]
I just started to add the color parameter to the dynamic icons and ran into the problem, that they where not dynamic any more after calling make.php.

To reproduce this, I did the following:
- made a new clone from github
- switched to the docu pages
- tested, that the dynamic icons where working on the Design/Icons page: They where working ok
- called make.php in the browser
- did a reload of the docu/Design/Icons page: The icons wheren't dynamic any more

**Comment by msinn** [comment]
Found out: all min.js files contain only:

```
/* smartVISU, Martin Gleiß, 2012 - 2015, GPL [http://www.gnu.de] */
window.console&&window.console.log){

window.console.log('Closure Compiler Stats:\n-----------------------\nOriginal Size: \nOriginal Gzip Size: \nCompressed Size: \nCompressed Gzip Size: \nCompile Time: \nGenerated: 2016/09/10 11:37:07 CEST');

}

```

**Comment by msinn** [comment]
Copied make.php from v2.7. Doesn't work either.

**Comment by msinn** [comment]
Ich habe vor einigen Minuten aus Verzweiflung Reload auf der make.php Seite gedrückt und die min.js Dateien wurden richtig gebaut. ??????

Gerade eben habe ich noch mal Reload gedrückt und bekomme wieder die fehlerhaften Dateien.

Die Ausgabe der make.php Seite enthält dann auch keine Dateigrößen:

```
lib/base/base.js
Original: , Original Gzip: , Compressed: , Compressed Gzip:
```

**Comment by psilo909** [comment]
laut @smaiLee packt der Google Webservice dahinter nicht zu oft hintereinander. Warte mal 30 min und mach nochmal.. Ich hatte das gleiche Problem, warten hat es gelöst-

**Comment by msinn** [comment]
Danke,

vielleicht sollte make.php dann die funktionierenden min.js Dateien zumindest nicht mit Mist überschreiben.

**Comment by smaiLee** [comment]
> vielleicht sollte make.php dann die funktionierenden min.js Dateien zumindest nicht mit Mist überschreiben.

Habe ich mir auchschon gedacht.
Aber noch lieber wäre mir für einen späteren Release die Ablösung durch eine interne Lösung ohne Webservice. Deshalb habe ich keine Zeit darauf verwendet, dies genauer anzuschauen.

**Comment by msinn** [comment]
ok. Ich mach dann aus dem Bug mal ein Improve.

**Comment by Morg42** [comment]
Für eine interne Lösung wäre https://github.com/google/closure-compiler-js ggf. ein Ansatzpunkt. Blicke aber beim "request-forming" noch nicht ausreichend durch, um es auf die Schnelle selbst zu machen.

**Comment by smaiLee** [comment]
duplicate of #27
