### ISSUE TITLE
JavaScript exceptions instead of showing status on website for some errors

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#97]
Some server side errors generate JavaScript exception instead of beieng reported as error status on the website.
Problem is that [base.js](https://github.com/Martin-Gleiss/smartvisu/blob/master/lib/base/base.js#L663-L669) expects a JSON error object, but e.g. php errors are written out as html.

I've made a dirty workaround by checking if the response is JSON and otherwise make a JSON object out of it.
But I'm sure there is a better solution.

**Comment by wvhn** [comment]
Error handling for server side errors has been improved again w/ #500 .  No further needs as of now.
