### ISSUE TITLE
Time displayed on top right corner should be server time, not browser time

### ISSUE THREAD

**Issue by lolouk44** [Martin-Gleiss/smartvisu#99]
I think this is more an enhancement request than an issue, but I think the time displayed on top right corner should be server time, not browser time.
This would make more sense since we're mainly displaying statuses of sensors which are in one location (normally closed to where the server is, or at least in the same timezone).
This would also make more sense when accessing from abroad....

**Comment by smaiLee** [comment]
I made this configurable:
You can select "server" as time source on configuration - interface - texts.
Default is "client", so w/o configuration change everything will remain unaffected.
